// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cluster.sql

package sqlc

import (
	"context"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (
    name,
    ipv4_address,
    public_key,
    private_key_ref,
    organization_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
 )
RETURNING id, name, ipv4_address, public_key, private_key_ref, organization_id, created_at, updated_at
`

type CreateClusterParams struct {
	Name           string
	Ipv4Address    string
	PublicKey      string
	PrivateKeyRef  string
	OrganizationID int64
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, createCluster,
		arg.Name,
		arg.Ipv4Address,
		arg.PublicKey,
		arg.PrivateKeyRef,
		arg.OrganizationID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ipv4Address,
		&i.PublicKey,
		&i.PrivateKeyRef,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :exec
DELETE
FROM clusters
WHERE id = $1
`

func (q *Queries) DeleteCluster(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCluster, id)
	return err
}

const getCluster = `-- name: GetCluster :one
SELECT id, name, ipv4_address, public_key, private_key_ref, organization_id, created_at, updated_at
FROM clusters
WHERE id = $1
`

func (q *Queries) GetCluster(ctx context.Context, id int64) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ipv4Address,
		&i.PublicKey,
		&i.PrivateKeyRef,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
