// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cluster.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (
    name,
    ipv4_address,
    public_key,
    private_key,
    organization_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
 )
RETURNING id, name, ipv4_address, public_key, private_key, organization_id, created_at, updated_at
`

type CreateClusterParams struct {
	Name           string
	Ipv4Address    sql.NullString
	PublicKey      sql.NullString
	PrivateKey     sql.NullString
	OrganizationID int64
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, createCluster,
		arg.Name,
		arg.Ipv4Address,
		arg.PublicKey,
		arg.PrivateKey,
		arg.OrganizationID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ipv4Address,
		&i.PublicKey,
		&i.PrivateKey,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :exec
DELETE
FROM clusters
WHERE id = $1
`

func (q *Queries) DeleteCluster(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCluster, id)
	return err
}

const getCluster = `-- name: GetCluster :one
SELECT id, name, ipv4_address, public_key, private_key, organization_id, created_at, updated_at
FROM clusters
WHERE id = $1
`

func (q *Queries) GetCluster(ctx context.Context, id int64) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ipv4Address,
		&i.PublicKey,
		&i.PrivateKey,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationClusters = `-- name: GetOrganizationClusters :many
SELECT
    clusters.id as id,
    clusters.name as name,
    clusters.ipv4_address as ipv4_address,
    clusters.public_key as public_key,
    clusters.private_key as private_key,
    clusters.organization_id as organization_id
FROM clusters
WHERE clusters.organization_id = $1
`

type GetOrganizationClustersRow struct {
	ID             int64
	Name           string
	Ipv4Address    sql.NullString
	PublicKey      sql.NullString
	PrivateKey     sql.NullString
	OrganizationID int64
}

func (q *Queries) GetOrganizationClusters(ctx context.Context, organizationID int64) ([]GetOrganizationClustersRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizationClusters, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationClustersRow
	for rows.Next() {
		var i GetOrganizationClustersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ipv4Address,
			&i.PublicKey,
			&i.PrivateKey,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClusterIPv4Address = `-- name: UpdateClusterIPv4Address :exec
UPDATE clusters
SET
    ipv4_address = $1
WHERE id = $2
`

type UpdateClusterIPv4AddressParams struct {
	Ipv4Address sql.NullString
	ID          int64
}

func (q *Queries) UpdateClusterIPv4Address(ctx context.Context, arg UpdateClusterIPv4AddressParams) error {
	_, err := q.db.ExecContext(ctx, updateClusterIPv4Address, arg.Ipv4Address, arg.ID)
	return err
}

const updateClusterPublicPrivateKeys = `-- name: UpdateClusterPublicPrivateKeys :exec
UPDATE clusters
SET
    public_key = $1,
    private_key = $2
WHERE id = $3
`

type UpdateClusterPublicPrivateKeysParams struct {
	PublicKey  sql.NullString
	PrivateKey sql.NullString
	ID         int64
}

func (q *Queries) UpdateClusterPublicPrivateKeys(ctx context.Context, arg UpdateClusterPublicPrivateKeysParams) error {
	_, err := q.db.ExecContext(ctx, updateClusterPublicPrivateKeys, arg.PublicKey, arg.PrivateKey, arg.ID)
	return err
}
