// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Cluster struct {
	ID             int64
	Name           string
	Ipv4Address    string
	PublicKey      string
	PrivateKeyRef  string
	OrganizationID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Environment struct {
	ID        int64
	Name      string
	Slug      string
	ProjectID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Organization struct {
	ID        int64
	Name      string
	Slug      string
	OwnerID   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID             int64
	Name           string
	OrganizationID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID           int64
	BetterAuthID string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
