// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package sqlc

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name,
    organization_id
) VALUES (
    $1,
    $2
)
RETURNING id, name, organization_id, created_at, updated_at
`

type CreateProjectParams struct {
	Name           string
	OrganizationID int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationProjects = `-- name: GetOrganizationProjects :many
SELECT
    projects.id as id,
    projects.name as name,
    projects.organization_id as organization_id
FROM projects
INNER JOIN organizations ON projects.organization_id = organizations.id
WHERE projects.organization_id = $1
`

type GetOrganizationProjectsRow struct {
	ID             int64
	Name           string
	OrganizationID int64
}

func (q *Queries) GetOrganizationProjects(ctx context.Context, organizationID int64) ([]GetOrganizationProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizationProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationProjectsRow
	for rows.Next() {
		var i GetOrganizationProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.OrganizationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
