// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" (
    better_auth_id
) VALUES (
    $1
)
RETURNING id, better_auth_id
`

func (q *Queries) CreateUser(ctx context.Context, betterAuthID string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, betterAuthID)
	var i User
	err := row.Scan(&i.ID, &i.BetterAuthID)
	return i, err
}

const getUserByBetterAuthId = `-- name: GetUserByBetterAuthId :one
SELECT id, better_auth_id
FROM "users"
WHERE better_auth_id = $1
`

func (q *Queries) GetUserByBetterAuthId(ctx context.Context, betterAuthID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByBetterAuthId, betterAuthID)
	var i User
	err := row.Scan(&i.ID, &i.BetterAuthID)
	return i, err
}
