// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.5
// source: internal/core/infrastructure/grpc/proto/v1/build_log.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuildLogService_StreamBuildLogs_FullMethodName = "/proto.v1.BuildLogService/StreamBuildLogs"
)

// BuildLogServiceClient is the client API for BuildLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuildLogServiceClient interface {
	StreamBuildLogs(ctx context.Context, in *StreamBuildLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamBuildLogResponse], error)
}

type buildLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildLogServiceClient(cc grpc.ClientConnInterface) BuildLogServiceClient {
	return &buildLogServiceClient{cc}
}

func (c *buildLogServiceClient) StreamBuildLogs(ctx context.Context, in *StreamBuildLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamBuildLogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BuildLogService_ServiceDesc.Streams[0], BuildLogService_StreamBuildLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBuildLogRequest, StreamBuildLogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuildLogService_StreamBuildLogsClient = grpc.ServerStreamingClient[StreamBuildLogResponse]

// BuildLogServiceServer is the server API for BuildLogService service.
// All implementations must embed UnimplementedBuildLogServiceServer
// for forward compatibility.
type BuildLogServiceServer interface {
	StreamBuildLogs(*StreamBuildLogRequest, grpc.ServerStreamingServer[StreamBuildLogResponse]) error
	mustEmbedUnimplementedBuildLogServiceServer()
}

// UnimplementedBuildLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildLogServiceServer struct{}

func (UnimplementedBuildLogServiceServer) StreamBuildLogs(*StreamBuildLogRequest, grpc.ServerStreamingServer[StreamBuildLogResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamBuildLogs not implemented")
}
func (UnimplementedBuildLogServiceServer) mustEmbedUnimplementedBuildLogServiceServer() {}
func (UnimplementedBuildLogServiceServer) testEmbeddedByValue()                         {}

// UnsafeBuildLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildLogServiceServer will
// result in compilation errors.
type UnsafeBuildLogServiceServer interface {
	mustEmbedUnimplementedBuildLogServiceServer()
}

func RegisterBuildLogServiceServer(s grpc.ServiceRegistrar, srv BuildLogServiceServer) {
	// If the following call panics, it indicates UnimplementedBuildLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildLogService_ServiceDesc, srv)
}

func _BuildLogService_StreamBuildLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBuildLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BuildLogServiceServer).StreamBuildLogs(m, &grpc.GenericServerStream[StreamBuildLogRequest, StreamBuildLogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuildLogService_StreamBuildLogsServer = grpc.ServerStreamingServer[StreamBuildLogResponse]

// BuildLogService_ServiceDesc is the grpc.ServiceDesc for BuildLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.BuildLogService",
	HandlerType: (*BuildLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBuildLogs",
			Handler:       _BuildLogService_StreamBuildLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/core/infrastructure/grpc/proto/v1/build_log.proto",
}
