// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/core/infrastructure/grpc/proto/v1/build_log.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamBuildLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       int64                  `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBuildLogRequest) Reset() {
	*x = StreamBuildLogRequest{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBuildLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBuildLogRequest) ProtoMessage() {}

func (x *StreamBuildLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBuildLogRequest.ProtoReflect.Descriptor instead.
func (*StreamBuildLogRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDescGZIP(), []int{0}
}

func (x *StreamBuildLogRequest) GetBuildId() int64 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

type StreamBuildLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBuildLogResponse) Reset() {
	*x = StreamBuildLogResponse{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBuildLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBuildLogResponse) ProtoMessage() {}

func (x *StreamBuildLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBuildLogResponse.ProtoReflect.Descriptor instead.
func (*StreamBuildLogResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDescGZIP(), []int{1}
}

func (x *StreamBuildLogResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_internal_core_infrastructure_grpc_proto_v1_build_log_proto protoreflect.FileDescriptor

const file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDesc = "" +
	"\n" +
	":internal/core/infrastructure/grpc/proto/v1/build_log.proto\x12\bproto.v1\"2\n" +
	"\x15StreamBuildLogRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\x03R\abuildId\".\n" +
	"\x16StreamBuildLogResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2i\n" +
	"\x0fBuildLogService\x12V\n" +
	"\x0fStreamBuildLogs\x12\x1f.proto.v1.StreamBuildLogRequest\x1a .proto.v1.StreamBuildLogResponse0\x01B:Z8starliner.app/internal/core/infrastructure/grpc/proto/v1b\x06proto3"

var (
	file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDescOnce sync.Once
	file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDescData []byte
)

func file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDescGZIP() []byte {
	file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDescOnce.Do(func() {
		file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDesc)))
	})
	return file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDescData
}

var file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_goTypes = []any{
	(*StreamBuildLogRequest)(nil),  // 0: proto.v1.StreamBuildLogRequest
	(*StreamBuildLogResponse)(nil), // 1: proto.v1.StreamBuildLogResponse
}
var file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_depIdxs = []int32{
	0, // 0: proto.v1.BuildLogService.StreamBuildLogs:input_type -> proto.v1.StreamBuildLogRequest
	1, // 1: proto.v1.BuildLogService.StreamBuildLogs:output_type -> proto.v1.StreamBuildLogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_init() }
func file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_init() {
	if File_internal_core_infrastructure_grpc_proto_v1_build_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_goTypes,
		DependencyIndexes: file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_depIdxs,
		MessageInfos:      file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_msgTypes,
	}.Build()
	File_internal_core_infrastructure_grpc_proto_v1_build_log_proto = out.File
	file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_goTypes = nil
	file_internal_core_infrastructure_grpc_proto_v1_build_log_proto_depIdxs = nil
}
