// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/core/infrastructure/grpc/proto/v1/cluster_tty.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterTerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterTerminalSize) Reset() {
	*x = ClusterTerminalSize{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterTerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterTerminalSize) ProtoMessage() {}

func (x *ClusterTerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterTerminalSize.ProtoReflect.Descriptor instead.
func (*ClusterTerminalSize) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterTerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ClusterTerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type OpenClusterTTYRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OpenClusterTTYRequest_Session
	//	*OpenClusterTTYRequest_Stdin
	//	*OpenClusterTTYRequest_Size
	Payload       isOpenClusterTTYRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenClusterTTYRequest) Reset() {
	*x = OpenClusterTTYRequest{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenClusterTTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenClusterTTYRequest) ProtoMessage() {}

func (x *OpenClusterTTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenClusterTTYRequest.ProtoReflect.Descriptor instead.
func (*OpenClusterTTYRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescGZIP(), []int{1}
}

func (x *OpenClusterTTYRequest) GetPayload() isOpenClusterTTYRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpenClusterTTYRequest) GetSession() *ClusterTTYSession {
	if x != nil {
		if x, ok := x.Payload.(*OpenClusterTTYRequest_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *OpenClusterTTYRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*OpenClusterTTYRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *OpenClusterTTYRequest) GetSize() *ClusterTerminalSize {
	if x != nil {
		if x, ok := x.Payload.(*OpenClusterTTYRequest_Size); ok {
			return x.Size
		}
	}
	return nil
}

type isOpenClusterTTYRequest_Payload interface {
	isOpenClusterTTYRequest_Payload()
}

type OpenClusterTTYRequest_Session struct {
	Session *ClusterTTYSession `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type OpenClusterTTYRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type OpenClusterTTYRequest_Size struct {
	Size *ClusterTerminalSize `protobuf:"bytes,3,opt,name=size,proto3,oneof"`
}

func (*OpenClusterTTYRequest_Session) isOpenClusterTTYRequest_Payload() {}

func (*OpenClusterTTYRequest_Stdin) isOpenClusterTTYRequest_Payload() {}

func (*OpenClusterTTYRequest_Size) isOpenClusterTTYRequest_Payload() {}

type ClusterTTYSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	PemKey        []byte                 `protobuf:"bytes,3,opt,name=pemKey,proto3" json:"pemKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterTTYSession) Reset() {
	*x = ClusterTTYSession{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterTTYSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterTTYSession) ProtoMessage() {}

func (x *ClusterTTYSession) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterTTYSession.ProtoReflect.Descriptor instead.
func (*ClusterTTYSession) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterTTYSession) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClusterTTYSession) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ClusterTTYSession) GetPemKey() []byte {
	if x != nil {
		return x.PemKey
	}
	return nil
}

type OpenClusterTTYResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenClusterTTYResponse) Reset() {
	*x = OpenClusterTTYResponse{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenClusterTTYResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenClusterTTYResponse) ProtoMessage() {}

func (x *OpenClusterTTYResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenClusterTTYResponse.ProtoReflect.Descriptor instead.
func (*OpenClusterTTYResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescGZIP(), []int{3}
}

func (x *OpenClusterTTYResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

var File_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto protoreflect.FileDescriptor

const file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDesc = "" +
	"\n" +
	"<internal/core/infrastructure/grpc/proto/v1/cluster_tty.proto\x12\bproto.v1\"=\n" +
	"\x13ClusterTerminalSize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\xa8\x01\n" +
	"\x15OpenClusterTTYRequest\x127\n" +
	"\asession\x18\x01 \x01(\v2\x1b.proto.v1.ClusterTTYSessionH\x00R\asession\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x123\n" +
	"\x04size\x18\x03 \x01(\v2\x1d.proto.v1.ClusterTerminalSizeH\x00R\x04sizeB\t\n" +
	"\apayload\"O\n" +
	"\x11ClusterTTYSession\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x16\n" +
	"\x06pemKey\x18\x03 \x01(\fR\x06pemKey\"0\n" +
	"\x16OpenClusterTTYResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout2e\n" +
	"\x11ClusterTTYService\x12P\n" +
	"\aOpenTTY\x12\x1f.proto.v1.OpenClusterTTYRequest\x1a .proto.v1.OpenClusterTTYResponse(\x010\x01B:Z8starliner.app/internal/core/infrastructure/grpc/proto/v1b\x06proto3"

var (
	file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescOnce sync.Once
	file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescData []byte
)

func file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescGZIP() []byte {
	file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescOnce.Do(func() {
		file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDesc)))
	})
	return file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDescData
}

var file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_goTypes = []any{
	(*ClusterTerminalSize)(nil),    // 0: proto.v1.ClusterTerminalSize
	(*OpenClusterTTYRequest)(nil),  // 1: proto.v1.OpenClusterTTYRequest
	(*ClusterTTYSession)(nil),      // 2: proto.v1.ClusterTTYSession
	(*OpenClusterTTYResponse)(nil), // 3: proto.v1.OpenClusterTTYResponse
}
var file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_depIdxs = []int32{
	2, // 0: proto.v1.OpenClusterTTYRequest.session:type_name -> proto.v1.ClusterTTYSession
	0, // 1: proto.v1.OpenClusterTTYRequest.size:type_name -> proto.v1.ClusterTerminalSize
	1, // 2: proto.v1.ClusterTTYService.OpenTTY:input_type -> proto.v1.OpenClusterTTYRequest
	3, // 3: proto.v1.ClusterTTYService.OpenTTY:output_type -> proto.v1.OpenClusterTTYResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_init() }
func file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_init() {
	if File_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto != nil {
		return
	}
	file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes[1].OneofWrappers = []any{
		(*OpenClusterTTYRequest_Session)(nil),
		(*OpenClusterTTYRequest_Stdin)(nil),
		(*OpenClusterTTYRequest_Size)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_goTypes,
		DependencyIndexes: file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_depIdxs,
		MessageInfos:      file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_msgTypes,
	}.Build()
	File_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto = out.File
	file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_goTypes = nil
	file_internal_core_infrastructure_grpc_proto_v1_cluster_tty_proto_depIdxs = nil
}
