// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/core/infrastructure/grpc/proto/v1/cluster_tty.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterTTYService_OpenTTY_FullMethodName = "/proto.v1.ClusterTTYService/OpenTTY"
)

// ClusterTTYServiceClient is the client API for ClusterTTYService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterTTYServiceClient interface {
	OpenTTY(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenClusterTTYRequest, OpenClusterTTYResponse], error)
}

type clusterTTYServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterTTYServiceClient(cc grpc.ClientConnInterface) ClusterTTYServiceClient {
	return &clusterTTYServiceClient{cc}
}

func (c *clusterTTYServiceClient) OpenTTY(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenClusterTTYRequest, OpenClusterTTYResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterTTYService_ServiceDesc.Streams[0], ClusterTTYService_OpenTTY_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenClusterTTYRequest, OpenClusterTTYResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterTTYService_OpenTTYClient = grpc.BidiStreamingClient[OpenClusterTTYRequest, OpenClusterTTYResponse]

// ClusterTTYServiceServer is the server API for ClusterTTYService service.
// All implementations must embed UnimplementedClusterTTYServiceServer
// for forward compatibility.
type ClusterTTYServiceServer interface {
	OpenTTY(grpc.BidiStreamingServer[OpenClusterTTYRequest, OpenClusterTTYResponse]) error
	mustEmbedUnimplementedClusterTTYServiceServer()
}

// UnimplementedClusterTTYServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterTTYServiceServer struct{}

func (UnimplementedClusterTTYServiceServer) OpenTTY(grpc.BidiStreamingServer[OpenClusterTTYRequest, OpenClusterTTYResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenTTY not implemented")
}
func (UnimplementedClusterTTYServiceServer) mustEmbedUnimplementedClusterTTYServiceServer() {}
func (UnimplementedClusterTTYServiceServer) testEmbeddedByValue()                           {}

// UnsafeClusterTTYServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterTTYServiceServer will
// result in compilation errors.
type UnsafeClusterTTYServiceServer interface {
	mustEmbedUnimplementedClusterTTYServiceServer()
}

func RegisterClusterTTYServiceServer(s grpc.ServiceRegistrar, srv ClusterTTYServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterTTYServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterTTYService_ServiceDesc, srv)
}

func _ClusterTTYService_OpenTTY_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterTTYServiceServer).OpenTTY(&grpc.GenericServerStream[OpenClusterTTYRequest, OpenClusterTTYResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterTTYService_OpenTTYServer = grpc.BidiStreamingServer[OpenClusterTTYRequest, OpenClusterTTYResponse]

// ClusterTTYService_ServiceDesc is the grpc.ServiceDesc for ClusterTTYService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterTTYService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.ClusterTTYService",
	HandlerType: (*ClusterTTYServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenTTY",
			Handler:       _ClusterTTYService_OpenTTY_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/core/infrastructure/grpc/proto/v1/cluster_tty.proto",
}
