// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.5
// source: internal/core/infrastructure/grpc/proto/v1/cluster_log.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvisioningLogService_StreamingProvisioningLogs_FullMethodName = "/proto.v1.ProvisioningLogService/StreamingProvisioningLogs"
)

// ProvisioningLogServiceClient is the client API for ProvisioningLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvisioningLogServiceClient interface {
	StreamingProvisioningLogs(ctx context.Context, in *StreamProvisioningLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamProvisioningLogResponse], error)
}

type provisioningLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisioningLogServiceClient(cc grpc.ClientConnInterface) ProvisioningLogServiceClient {
	return &provisioningLogServiceClient{cc}
}

func (c *provisioningLogServiceClient) StreamingProvisioningLogs(ctx context.Context, in *StreamProvisioningLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamProvisioningLogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProvisioningLogService_ServiceDesc.Streams[0], ProvisioningLogService_StreamingProvisioningLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProvisioningLogRequest, StreamProvisioningLogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvisioningLogService_StreamingProvisioningLogsClient = grpc.ServerStreamingClient[StreamProvisioningLogResponse]

// ProvisioningLogServiceServer is the server API for ProvisioningLogService service.
// All implementations must embed UnimplementedProvisioningLogServiceServer
// for forward compatibility.
type ProvisioningLogServiceServer interface {
	StreamingProvisioningLogs(*StreamProvisioningLogRequest, grpc.ServerStreamingServer[StreamProvisioningLogResponse]) error
	mustEmbedUnimplementedProvisioningLogServiceServer()
}

// UnimplementedProvisioningLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisioningLogServiceServer struct{}

func (UnimplementedProvisioningLogServiceServer) StreamingProvisioningLogs(*StreamProvisioningLogRequest, grpc.ServerStreamingServer[StreamProvisioningLogResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamingProvisioningLogs not implemented")
}
func (UnimplementedProvisioningLogServiceServer) mustEmbedUnimplementedProvisioningLogServiceServer() {
}
func (UnimplementedProvisioningLogServiceServer) testEmbeddedByValue() {}

// UnsafeProvisioningLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisioningLogServiceServer will
// result in compilation errors.
type UnsafeProvisioningLogServiceServer interface {
	mustEmbedUnimplementedProvisioningLogServiceServer()
}

func RegisterProvisioningLogServiceServer(s grpc.ServiceRegistrar, srv ProvisioningLogServiceServer) {
	// If the following call panics, it indicates UnimplementedProvisioningLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvisioningLogService_ServiceDesc, srv)
}

func _ProvisioningLogService_StreamingProvisioningLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProvisioningLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProvisioningLogServiceServer).StreamingProvisioningLogs(m, &grpc.GenericServerStream[StreamProvisioningLogRequest, StreamProvisioningLogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvisioningLogService_StreamingProvisioningLogsServer = grpc.ServerStreamingServer[StreamProvisioningLogResponse]

// ProvisioningLogService_ServiceDesc is the grpc.ServiceDesc for ProvisioningLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvisioningLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.ProvisioningLogService",
	HandlerType: (*ProvisioningLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingProvisioningLogs",
			Handler:       _ProvisioningLogService_StreamingProvisioningLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/core/infrastructure/grpc/proto/v1/cluster_log.proto",
}
