// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.5
// source: internal/core/infrastructure/grpc/proto/v1/deployment_status_log.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeploymentStatusLogService_StreamDeploymentStatusLogs_FullMethodName = "/proto.v1.DeploymentStatusLogService/StreamDeploymentStatusLogs"
)

// DeploymentStatusLogServiceClient is the client API for DeploymentStatusLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentStatusLogServiceClient interface {
	StreamDeploymentStatusLogs(ctx context.Context, in *StreamDeploymentStatusLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamDeploymentStatusLogsResponse], error)
}

type deploymentStatusLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentStatusLogServiceClient(cc grpc.ClientConnInterface) DeploymentStatusLogServiceClient {
	return &deploymentStatusLogServiceClient{cc}
}

func (c *deploymentStatusLogServiceClient) StreamDeploymentStatusLogs(ctx context.Context, in *StreamDeploymentStatusLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamDeploymentStatusLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeploymentStatusLogService_ServiceDesc.Streams[0], DeploymentStatusLogService_StreamDeploymentStatusLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDeploymentStatusLogsRequest, StreamDeploymentStatusLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeploymentStatusLogService_StreamDeploymentStatusLogsClient = grpc.ServerStreamingClient[StreamDeploymentStatusLogsResponse]

// DeploymentStatusLogServiceServer is the server API for DeploymentStatusLogService service.
// All implementations must embed UnimplementedDeploymentStatusLogServiceServer
// for forward compatibility.
type DeploymentStatusLogServiceServer interface {
	StreamDeploymentStatusLogs(*StreamDeploymentStatusLogsRequest, grpc.ServerStreamingServer[StreamDeploymentStatusLogsResponse]) error
	mustEmbedUnimplementedDeploymentStatusLogServiceServer()
}

// UnimplementedDeploymentStatusLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentStatusLogServiceServer struct{}

func (UnimplementedDeploymentStatusLogServiceServer) StreamDeploymentStatusLogs(*StreamDeploymentStatusLogsRequest, grpc.ServerStreamingServer[StreamDeploymentStatusLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamDeploymentStatusLogs not implemented")
}
func (UnimplementedDeploymentStatusLogServiceServer) mustEmbedUnimplementedDeploymentStatusLogServiceServer() {
}
func (UnimplementedDeploymentStatusLogServiceServer) testEmbeddedByValue() {}

// UnsafeDeploymentStatusLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentStatusLogServiceServer will
// result in compilation errors.
type UnsafeDeploymentStatusLogServiceServer interface {
	mustEmbedUnimplementedDeploymentStatusLogServiceServer()
}

func RegisterDeploymentStatusLogServiceServer(s grpc.ServiceRegistrar, srv DeploymentStatusLogServiceServer) {
	// If the following call panics, it indicates UnimplementedDeploymentStatusLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentStatusLogService_ServiceDesc, srv)
}

func _DeploymentStatusLogService_StreamDeploymentStatusLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDeploymentStatusLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeploymentStatusLogServiceServer).StreamDeploymentStatusLogs(m, &grpc.GenericServerStream[StreamDeploymentStatusLogsRequest, StreamDeploymentStatusLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeploymentStatusLogService_StreamDeploymentStatusLogsServer = grpc.ServerStreamingServer[StreamDeploymentStatusLogsResponse]

// DeploymentStatusLogService_ServiceDesc is the grpc.ServiceDesc for DeploymentStatusLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentStatusLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.DeploymentStatusLogService",
	HandlerType: (*DeploymentStatusLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDeploymentStatusLogs",
			Handler:       _DeploymentStatusLogService_StreamDeploymentStatusLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/core/infrastructure/grpc/proto/v1/deployment_status_log.proto",
}

const (
	IngressDeploymentStatusLogService_StreamIngressDeploymentStatusLogs_FullMethodName = "/proto.v1.IngressDeploymentStatusLogService/StreamIngressDeploymentStatusLogs"
)

// IngressDeploymentStatusLogServiceClient is the client API for IngressDeploymentStatusLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngressDeploymentStatusLogServiceClient interface {
	StreamIngressDeploymentStatusLogs(ctx context.Context, in *StreamIngressDeploymentStatusLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamIngressDeploymentStatusLogsResponse], error)
}

type ingressDeploymentStatusLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngressDeploymentStatusLogServiceClient(cc grpc.ClientConnInterface) IngressDeploymentStatusLogServiceClient {
	return &ingressDeploymentStatusLogServiceClient{cc}
}

func (c *ingressDeploymentStatusLogServiceClient) StreamIngressDeploymentStatusLogs(ctx context.Context, in *StreamIngressDeploymentStatusLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamIngressDeploymentStatusLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngressDeploymentStatusLogService_ServiceDesc.Streams[0], IngressDeploymentStatusLogService_StreamIngressDeploymentStatusLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamIngressDeploymentStatusLogsRequest, StreamIngressDeploymentStatusLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngressDeploymentStatusLogService_StreamIngressDeploymentStatusLogsClient = grpc.ServerStreamingClient[StreamIngressDeploymentStatusLogsResponse]

// IngressDeploymentStatusLogServiceServer is the server API for IngressDeploymentStatusLogService service.
// All implementations must embed UnimplementedIngressDeploymentStatusLogServiceServer
// for forward compatibility.
type IngressDeploymentStatusLogServiceServer interface {
	StreamIngressDeploymentStatusLogs(*StreamIngressDeploymentStatusLogsRequest, grpc.ServerStreamingServer[StreamIngressDeploymentStatusLogsResponse]) error
	mustEmbedUnimplementedIngressDeploymentStatusLogServiceServer()
}

// UnimplementedIngressDeploymentStatusLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngressDeploymentStatusLogServiceServer struct{}

func (UnimplementedIngressDeploymentStatusLogServiceServer) StreamIngressDeploymentStatusLogs(*StreamIngressDeploymentStatusLogsRequest, grpc.ServerStreamingServer[StreamIngressDeploymentStatusLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamIngressDeploymentStatusLogs not implemented")
}
func (UnimplementedIngressDeploymentStatusLogServiceServer) mustEmbedUnimplementedIngressDeploymentStatusLogServiceServer() {
}
func (UnimplementedIngressDeploymentStatusLogServiceServer) testEmbeddedByValue() {}

// UnsafeIngressDeploymentStatusLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngressDeploymentStatusLogServiceServer will
// result in compilation errors.
type UnsafeIngressDeploymentStatusLogServiceServer interface {
	mustEmbedUnimplementedIngressDeploymentStatusLogServiceServer()
}

func RegisterIngressDeploymentStatusLogServiceServer(s grpc.ServiceRegistrar, srv IngressDeploymentStatusLogServiceServer) {
	// If the following call panics, it indicates UnimplementedIngressDeploymentStatusLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngressDeploymentStatusLogService_ServiceDesc, srv)
}

func _IngressDeploymentStatusLogService_StreamIngressDeploymentStatusLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamIngressDeploymentStatusLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IngressDeploymentStatusLogServiceServer).StreamIngressDeploymentStatusLogs(m, &grpc.GenericServerStream[StreamIngressDeploymentStatusLogsRequest, StreamIngressDeploymentStatusLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngressDeploymentStatusLogService_StreamIngressDeploymentStatusLogsServer = grpc.ServerStreamingServer[StreamIngressDeploymentStatusLogsResponse]

// IngressDeploymentStatusLogService_ServiceDesc is the grpc.ServiceDesc for IngressDeploymentStatusLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngressDeploymentStatusLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.IngressDeploymentStatusLogService",
	HandlerType: (*IngressDeploymentStatusLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIngressDeploymentStatusLogs",
			Handler:       _IngressDeploymentStatusLogService_StreamIngressDeploymentStatusLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/core/infrastructure/grpc/proto/v1/deployment_status_log.proto",
}
