// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.5
// source: internal/core/infrastructure/grpc/proto/v1/deployment_status_log.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamDeploymentStatusLogsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName      string                 `protobuf:"bytes,2,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
	KubeconfigBase64 string                 `protobuf:"bytes,3,opt,name=kubeconfig_base64,json=kubeconfigBase64,proto3" json:"kubeconfig_base64,omitempty"`
	CommitHash       string                 `protobuf:"bytes,4,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamDeploymentStatusLogsRequest) Reset() {
	*x = StreamDeploymentStatusLogsRequest{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDeploymentStatusLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDeploymentStatusLogsRequest) ProtoMessage() {}

func (x *StreamDeploymentStatusLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDeploymentStatusLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamDeploymentStatusLogsRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDescGZIP(), []int{0}
}

func (x *StreamDeploymentStatusLogsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StreamDeploymentStatusLogsRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *StreamDeploymentStatusLogsRequest) GetKubeconfigBase64() string {
	if x != nil {
		return x.KubeconfigBase64
	}
	return ""
}

func (x *StreamDeploymentStatusLogsRequest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

type StreamDeploymentStatusLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDeploymentStatusLogsResponse) Reset() {
	*x = StreamDeploymentStatusLogsResponse{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDeploymentStatusLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDeploymentStatusLogsResponse) ProtoMessage() {}

func (x *StreamDeploymentStatusLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDeploymentStatusLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamDeploymentStatusLogsResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDescGZIP(), []int{1}
}

func (x *StreamDeploymentStatusLogsResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto protoreflect.FileDescriptor

const file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDesc = "" +
	"\n" +
	"Finternal/core/infrastructure/grpc/proto/v1/deployment_status_log.proto\x12\bproto.v1\"\xb2\x01\n" +
	"!StreamDeploymentStatusLogsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\frelease_name\x18\x02 \x01(\tR\vreleaseName\x12+\n" +
	"\x11kubeconfig_base64\x18\x03 \x01(\tR\x10kubeconfigBase64\x12\x1f\n" +
	"\vcommit_hash\x18\x04 \x01(\tR\n" +
	"commitHash\":\n" +
	"\"StreamDeploymentStatusLogsResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2\x97\x01\n" +
	"\x1aDeploymentStatusLogService\x12y\n" +
	"\x1aStreamDeploymentStatusLogs\x12+.proto.v1.StreamDeploymentStatusLogsRequest\x1a,.proto.v1.StreamDeploymentStatusLogsResponse0\x01B:Z8starliner.app/internal/core/infrastructure/grpc/proto/v1b\x06proto3"

var (
	file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDescOnce sync.Once
	file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDescData []byte
)

func file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDescGZIP() []byte {
	file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDescOnce.Do(func() {
		file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDesc)))
	})
	return file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDescData
}

var file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_goTypes = []any{
	(*StreamDeploymentStatusLogsRequest)(nil),  // 0: proto.v1.StreamDeploymentStatusLogsRequest
	(*StreamDeploymentStatusLogsResponse)(nil), // 1: proto.v1.StreamDeploymentStatusLogsResponse
}
var file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_depIdxs = []int32{
	0, // 0: proto.v1.DeploymentStatusLogService.StreamDeploymentStatusLogs:input_type -> proto.v1.StreamDeploymentStatusLogsRequest
	1, // 1: proto.v1.DeploymentStatusLogService.StreamDeploymentStatusLogs:output_type -> proto.v1.StreamDeploymentStatusLogsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_init() }
func file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_init() {
	if File_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_goTypes,
		DependencyIndexes: file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_depIdxs,
		MessageInfos:      file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_msgTypes,
	}.Build()
	File_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto = out.File
	file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_goTypes = nil
	file_internal_core_infrastructure_grpc_proto_v1_deployment_status_log_proto_depIdxs = nil
}
