// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/core/infrastructure/grpc/proto/v1/health.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Health int32

const (
	Health_HEALTH_UNSPECIFIED Health = 0
	Health_HEALTH_HEALTHY     Health = 1
	Health_HEALTH_UNHEALTHY   Health = 2
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_UNHEALTHY",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_HEALTHY":     1,
		"HEALTH_UNHEALTHY":   2,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_core_infrastructure_grpc_proto_v1_health_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_internal_core_infrastructure_grpc_proto_v1_health_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescGZIP(), []int{0}
}

type GetHealthStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId     int64                  `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Namespace        string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeploymentName   string                 `protobuf:"bytes,3,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	KubeconfigBase64 string                 `protobuf:"bytes,4,opt,name=kubeconfig_base64,json=kubeconfigBase64,proto3" json:"kubeconfig_base64,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetHealthStatusRequest) Reset() {
	*x = GetHealthStatusRequest{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthStatusRequest) ProtoMessage() {}

func (x *GetHealthStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthStatusRequest.ProtoReflect.Descriptor instead.
func (*GetHealthStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *GetHealthStatusRequest) GetDeploymentId() int64 {
	if x != nil {
		return x.DeploymentId
	}
	return 0
}

func (x *GetHealthStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetHealthStatusRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *GetHealthStatusRequest) GetKubeconfigBase64() string {
	if x != nil {
		return x.KubeconfigBase64
	}
	return ""
}

type GetHealthStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  int64                  `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Health        Health                 `protobuf:"varint,2,opt,name=health,proto3,enum=proto.v1.Health" json:"health,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthStatusResponse) Reset() {
	*x = GetHealthStatusResponse{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthStatusResponse) ProtoMessage() {}

func (x *GetHealthStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthStatusResponse.ProtoReflect.Descriptor instead.
func (*GetHealthStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *GetHealthStatusResponse) GetDeploymentId() int64 {
	if x != nil {
		return x.DeploymentId
	}
	return 0
}

func (x *GetHealthStatusResponse) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *GetHealthStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_core_infrastructure_grpc_proto_v1_health_proto protoreflect.FileDescriptor

const file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDesc = "" +
	"\n" +
	"7internal/core/infrastructure/grpc/proto/v1/health.proto\x12\bproto.v1\"\xb1\x01\n" +
	"\x16GetHealthStatusRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x03R\fdeploymentId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12'\n" +
	"\x0fdeployment_name\x18\x03 \x01(\tR\x0edeploymentName\x12+\n" +
	"\x11kubeconfig_base64\x18\x04 \x01(\tR\x10kubeconfigBase64\"\x80\x01\n" +
	"\x17GetHealthStatusResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x03R\fdeploymentId\x12(\n" +
	"\x06health\x18\x02 \x01(\x0e2\x10.proto.v1.HealthR\x06health\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status*J\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x022g\n" +
	"\rHealthService\x12V\n" +
	"\x0fGetHealthStatus\x12 .proto.v1.GetHealthStatusRequest\x1a!.proto.v1.GetHealthStatusResponseB:Z8starliner.app/internal/core/infrastructure/grpc/proto/v1b\x06proto3"

var (
	file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescOnce sync.Once
	file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescData []byte
)

func file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescGZIP() []byte {
	file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescOnce.Do(func() {
		file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDesc)))
	})
	return file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDescData
}

var file_internal_core_infrastructure_grpc_proto_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_core_infrastructure_grpc_proto_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_core_infrastructure_grpc_proto_v1_health_proto_goTypes = []any{
	(Health)(0),                     // 0: proto.v1.Health
	(*GetHealthStatusRequest)(nil),  // 1: proto.v1.GetHealthStatusRequest
	(*GetHealthStatusResponse)(nil), // 2: proto.v1.GetHealthStatusResponse
}
var file_internal_core_infrastructure_grpc_proto_v1_health_proto_depIdxs = []int32{
	0, // 0: proto.v1.GetHealthStatusResponse.health:type_name -> proto.v1.Health
	1, // 1: proto.v1.HealthService.GetHealthStatus:input_type -> proto.v1.GetHealthStatusRequest
	2, // 2: proto.v1.HealthService.GetHealthStatus:output_type -> proto.v1.GetHealthStatusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_core_infrastructure_grpc_proto_v1_health_proto_init() }
func file_internal_core_infrastructure_grpc_proto_v1_health_proto_init() {
	if File_internal_core_infrastructure_grpc_proto_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_core_infrastructure_grpc_proto_v1_health_proto_goTypes,
		DependencyIndexes: file_internal_core_infrastructure_grpc_proto_v1_health_proto_depIdxs,
		EnumInfos:         file_internal_core_infrastructure_grpc_proto_v1_health_proto_enumTypes,
		MessageInfos:      file_internal_core_infrastructure_grpc_proto_v1_health_proto_msgTypes,
	}.Build()
	File_internal_core_infrastructure_grpc_proto_v1_health_proto = out.File
	file_internal_core_infrastructure_grpc_proto_v1_health_proto_goTypes = nil
	file_internal_core_infrastructure_grpc_proto_v1_health_proto_depIdxs = nil
}
