// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/core/infrastructure/grpc/proto/v1/runner_auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveRunnerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRunnerIdRequest) Reset() {
	*x = ResolveRunnerIdRequest{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRunnerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRunnerIdRequest) ProtoMessage() {}

func (x *ResolveRunnerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRunnerIdRequest.ProtoReflect.Descriptor instead.
func (*ResolveRunnerIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRunnerIdRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResolveRunnerIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunnerId       int64                  `protobuf:"varint,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	OrganizationId int64                  `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveRunnerIdResponse) Reset() {
	*x = ResolveRunnerIdResponse{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRunnerIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRunnerIdResponse) ProtoMessage() {}

func (x *ResolveRunnerIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRunnerIdResponse.ProtoReflect.Descriptor instead.
func (*ResolveRunnerIdResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveRunnerIdResponse) GetRunnerId() int64 {
	if x != nil {
		return x.RunnerId
	}
	return 0
}

func (x *ResolveRunnerIdResponse) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

var File_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto protoreflect.FileDescriptor

const file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDesc = "" +
	"\n" +
	"<internal/core/infrastructure/grpc/proto/v1/runner_auth.proto\x12\bproto.v1\".\n" +
	"\x16ResolveRunnerIdRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"_\n" +
	"\x17ResolveRunnerIdResponse\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\x03R\brunnerId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\x03R\x0eorganizationId2k\n" +
	"\x11RunnerAuthService\x12V\n" +
	"\x0fResolveRunnerId\x12 .proto.v1.ResolveRunnerIdRequest\x1a!.proto.v1.ResolveRunnerIdResponseB:Z8starliner.app/internal/core/infrastructure/grpc/proto/v1b\x06proto3"

var (
	file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDescOnce sync.Once
	file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDescData []byte
)

func file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDescGZIP() []byte {
	file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDescOnce.Do(func() {
		file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDesc)))
	})
	return file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDescData
}

var file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_goTypes = []any{
	(*ResolveRunnerIdRequest)(nil),  // 0: proto.v1.ResolveRunnerIdRequest
	(*ResolveRunnerIdResponse)(nil), // 1: proto.v1.ResolveRunnerIdResponse
}
var file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_depIdxs = []int32{
	0, // 0: proto.v1.RunnerAuthService.ResolveRunnerId:input_type -> proto.v1.ResolveRunnerIdRequest
	1, // 1: proto.v1.RunnerAuthService.ResolveRunnerId:output_type -> proto.v1.ResolveRunnerIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_init() }
func file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_init() {
	if File_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_goTypes,
		DependencyIndexes: file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_depIdxs,
		MessageInfos:      file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_msgTypes,
	}.Build()
	File_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto = out.File
	file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_goTypes = nil
	file_internal_core_infrastructure_grpc_proto_v1_runner_auth_proto_depIdxs = nil
}
