// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/core/infrastructure/grpc/proto/v1/runner_auth.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerAuthService_ResolveRunnerId_FullMethodName = "/proto.v1.RunnerAuthService/ResolveRunnerId"
)

// RunnerAuthServiceClient is the client API for RunnerAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerAuthServiceClient interface {
	ResolveRunnerId(ctx context.Context, in *ResolveRunnerIdRequest, opts ...grpc.CallOption) (*ResolveRunnerIdResponse, error)
}

type runnerAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerAuthServiceClient(cc grpc.ClientConnInterface) RunnerAuthServiceClient {
	return &runnerAuthServiceClient{cc}
}

func (c *runnerAuthServiceClient) ResolveRunnerId(ctx context.Context, in *ResolveRunnerIdRequest, opts ...grpc.CallOption) (*ResolveRunnerIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveRunnerIdResponse)
	err := c.cc.Invoke(ctx, RunnerAuthService_ResolveRunnerId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerAuthServiceServer is the server API for RunnerAuthService service.
// All implementations must embed UnimplementedRunnerAuthServiceServer
// for forward compatibility.
type RunnerAuthServiceServer interface {
	ResolveRunnerId(context.Context, *ResolveRunnerIdRequest) (*ResolveRunnerIdResponse, error)
	mustEmbedUnimplementedRunnerAuthServiceServer()
}

// UnimplementedRunnerAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerAuthServiceServer struct{}

func (UnimplementedRunnerAuthServiceServer) ResolveRunnerId(context.Context, *ResolveRunnerIdRequest) (*ResolveRunnerIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveRunnerId not implemented")
}
func (UnimplementedRunnerAuthServiceServer) mustEmbedUnimplementedRunnerAuthServiceServer() {}
func (UnimplementedRunnerAuthServiceServer) testEmbeddedByValue()                           {}

// UnsafeRunnerAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerAuthServiceServer will
// result in compilation errors.
type UnsafeRunnerAuthServiceServer interface {
	mustEmbedUnimplementedRunnerAuthServiceServer()
}

func RegisterRunnerAuthServiceServer(s grpc.ServiceRegistrar, srv RunnerAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedRunnerAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerAuthService_ServiceDesc, srv)
}

func _RunnerAuthService_ResolveRunnerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRunnerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerAuthServiceServer).ResolveRunnerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerAuthService_ResolveRunnerId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerAuthServiceServer).ResolveRunnerId(ctx, req.(*ResolveRunnerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerAuthService_ServiceDesc is the grpc.ServiceDesc for RunnerAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.RunnerAuthService",
	HandlerType: (*RunnerAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveRunnerId",
			Handler:    _RunnerAuthService_ResolveRunnerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/core/infrastructure/grpc/proto/v1/runner_auth.proto",
}
