// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/core/infrastructure/grpc/proto/v1/tty.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescGZIP(), []int{0}
}

func (x *TerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type OpenTTYRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OpenTTYRequest_Session
	//	*OpenTTYRequest_Stdin
	//	*OpenTTYRequest_Size
	Payload       isOpenTTYRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTTYRequest) Reset() {
	*x = OpenTTYRequest{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTTYRequest) ProtoMessage() {}

func (x *OpenTTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTTYRequest.ProtoReflect.Descriptor instead.
func (*OpenTTYRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescGZIP(), []int{1}
}

func (x *OpenTTYRequest) GetPayload() isOpenTTYRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpenTTYRequest) GetSession() *TTYSession {
	if x != nil {
		if x, ok := x.Payload.(*OpenTTYRequest_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *OpenTTYRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*OpenTTYRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *OpenTTYRequest) GetSize() *TerminalSize {
	if x != nil {
		if x, ok := x.Payload.(*OpenTTYRequest_Size); ok {
			return x.Size
		}
	}
	return nil
}

type isOpenTTYRequest_Payload interface {
	isOpenTTYRequest_Payload()
}

type OpenTTYRequest_Session struct {
	Session *TTYSession `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type OpenTTYRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type OpenTTYRequest_Size struct {
	Size *TerminalSize `protobuf:"bytes,3,opt,name=size,proto3,oneof"`
}

func (*OpenTTYRequest_Session) isOpenTTYRequest_Payload() {}

func (*OpenTTYRequest_Stdin) isOpenTTYRequest_Payload() {}

func (*OpenTTYRequest_Size) isOpenTTYRequest_Payload() {}

type TTYSession struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName      string                 `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	KubeconfigBase64 string                 `protobuf:"bytes,3,opt,name=kubeconfigBase64,proto3" json:"kubeconfigBase64,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TTYSession) Reset() {
	*x = TTYSession{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTYSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTYSession) ProtoMessage() {}

func (x *TTYSession) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTYSession.ProtoReflect.Descriptor instead.
func (*TTYSession) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescGZIP(), []int{2}
}

func (x *TTYSession) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TTYSession) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *TTYSession) GetKubeconfigBase64() string {
	if x != nil {
		return x.KubeconfigBase64
	}
	return ""
}

type OpenTTYResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTTYResponse) Reset() {
	*x = OpenTTYResponse{}
	mi := &file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTTYResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTTYResponse) ProtoMessage() {}

func (x *OpenTTYResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTTYResponse.ProtoReflect.Descriptor instead.
func (*OpenTTYResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescGZIP(), []int{3}
}

func (x *OpenTTYResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

var File_internal_core_infrastructure_grpc_proto_v1_tty_proto protoreflect.FileDescriptor

const file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDesc = "" +
	"\n" +
	"4internal/core/infrastructure/grpc/proto/v1/tty.proto\x12\bproto.v1\"6\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x93\x01\n" +
	"\x0eOpenTTYRequest\x120\n" +
	"\asession\x18\x01 \x01(\v2\x14.proto.v1.TTYSessionH\x00R\asession\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12,\n" +
	"\x04size\x18\x03 \x01(\v2\x16.proto.v1.TerminalSizeH\x00R\x04sizeB\t\n" +
	"\apayload\"x\n" +
	"\n" +
	"TTYSession\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vreleaseName\x18\x02 \x01(\tR\vreleaseName\x12*\n" +
	"\x10kubeconfigBase64\x18\x03 \x01(\tR\x10kubeconfigBase64\")\n" +
	"\x0fOpenTTYResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout2P\n" +
	"\n" +
	"TTYService\x12B\n" +
	"\aOpenTTY\x12\x18.proto.v1.OpenTTYRequest\x1a\x19.proto.v1.OpenTTYResponse(\x010\x01B:Z8starliner.app/internal/core/infrastructure/grpc/proto/v1b\x06proto3"

var (
	file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescOnce sync.Once
	file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescData []byte
)

func file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescGZIP() []byte {
	file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescOnce.Do(func() {
		file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDesc)))
	})
	return file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDescData
}

var file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_core_infrastructure_grpc_proto_v1_tty_proto_goTypes = []any{
	(*TerminalSize)(nil),    // 0: proto.v1.TerminalSize
	(*OpenTTYRequest)(nil),  // 1: proto.v1.OpenTTYRequest
	(*TTYSession)(nil),      // 2: proto.v1.TTYSession
	(*OpenTTYResponse)(nil), // 3: proto.v1.OpenTTYResponse
}
var file_internal_core_infrastructure_grpc_proto_v1_tty_proto_depIdxs = []int32{
	2, // 0: proto.v1.OpenTTYRequest.session:type_name -> proto.v1.TTYSession
	0, // 1: proto.v1.OpenTTYRequest.size:type_name -> proto.v1.TerminalSize
	1, // 2: proto.v1.TTYService.OpenTTY:input_type -> proto.v1.OpenTTYRequest
	3, // 3: proto.v1.TTYService.OpenTTY:output_type -> proto.v1.OpenTTYResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_core_infrastructure_grpc_proto_v1_tty_proto_init() }
func file_internal_core_infrastructure_grpc_proto_v1_tty_proto_init() {
	if File_internal_core_infrastructure_grpc_proto_v1_tty_proto != nil {
		return
	}
	file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes[1].OneofWrappers = []any{
		(*OpenTTYRequest_Session)(nil),
		(*OpenTTYRequest_Stdin)(nil),
		(*OpenTTYRequest_Size)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDesc), len(file_internal_core_infrastructure_grpc_proto_v1_tty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_core_infrastructure_grpc_proto_v1_tty_proto_goTypes,
		DependencyIndexes: file_internal_core_infrastructure_grpc_proto_v1_tty_proto_depIdxs,
		MessageInfos:      file_internal_core_infrastructure_grpc_proto_v1_tty_proto_msgTypes,
	}.Build()
	File_internal_core_infrastructure_grpc_proto_v1_tty_proto = out.File
	file_internal_core_infrastructure_grpc_proto_v1_tty_proto_goTypes = nil
	file_internal_core_infrastructure_grpc_proto_v1_tty_proto_depIdxs = nil
}
