// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/core/infrastructure/grpc/proto/v1/tty.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TTYService_OpenTTY_FullMethodName = "/proto.v1.TTYService/OpenTTY"
)

// TTYServiceClient is the client API for TTYService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TTYServiceClient interface {
	OpenTTY(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenTTYRequest, OpenTTYResponse], error)
}

type tTYServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTTYServiceClient(cc grpc.ClientConnInterface) TTYServiceClient {
	return &tTYServiceClient{cc}
}

func (c *tTYServiceClient) OpenTTY(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenTTYRequest, OpenTTYResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTYService_ServiceDesc.Streams[0], TTYService_OpenTTY_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenTTYRequest, OpenTTYResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTYService_OpenTTYClient = grpc.BidiStreamingClient[OpenTTYRequest, OpenTTYResponse]

// TTYServiceServer is the server API for TTYService service.
// All implementations must embed UnimplementedTTYServiceServer
// for forward compatibility.
type TTYServiceServer interface {
	OpenTTY(grpc.BidiStreamingServer[OpenTTYRequest, OpenTTYResponse]) error
	mustEmbedUnimplementedTTYServiceServer()
}

// UnimplementedTTYServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTYServiceServer struct{}

func (UnimplementedTTYServiceServer) OpenTTY(grpc.BidiStreamingServer[OpenTTYRequest, OpenTTYResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenTTY not implemented")
}
func (UnimplementedTTYServiceServer) mustEmbedUnimplementedTTYServiceServer() {}
func (UnimplementedTTYServiceServer) testEmbeddedByValue()                    {}

// UnsafeTTYServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTYServiceServer will
// result in compilation errors.
type UnsafeTTYServiceServer interface {
	mustEmbedUnimplementedTTYServiceServer()
}

func RegisterTTYServiceServer(s grpc.ServiceRegistrar, srv TTYServiceServer) {
	// If the following call panics, it indicates UnimplementedTTYServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTYService_ServiceDesc, srv)
}

func _TTYService_OpenTTY_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TTYServiceServer).OpenTTY(&grpc.GenericServerStream[OpenTTYRequest, OpenTTYResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTYService_OpenTTYServer = grpc.BidiStreamingServer[OpenTTYRequest, OpenTTYResponse]

// TTYService_ServiceDesc is the grpc.ServiceDesc for TTYService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTYService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.TTYService",
	HandlerType: (*TTYServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenTTY",
			Handler:       _TTYService_OpenTTY_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/core/infrastructure/grpc/proto/v1/tty.proto",
}
