name: starliner

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    healthcheck:
      test: "curl -f http://localhost:80 || exit 1"
      interval: 5s
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./.docker/nginx/ssl/dev.starliner.app.crt:/etc/nginx/dev.starliner.app.crt:ro
      - ./.docker/nginx/ssl/dev.starliner.app.key:/etc/nginx/dev.starliner.app.key:ro
      - ./.docker/nginx/ssl/registry.dev.starliner.app.crt:/etc/nginx/registry.dev.starliner.app.crt:ro
      - ./.docker/nginx/ssl/registry.dev.starliner.app.key:/etc/nginx/registry.dev.starliner.app.key:ro
    depends_on:
      - client
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal

  client:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/client/Dockerfile
      target: development-dependencies-env
    depends_on:
      auth-db:
        condition: service_healthy
    command: sh -c "npm run dev -- --host 0.0.0.0"
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-HI2YJBqHK0Zz0ibFf564RgKPCFlsBfO9}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-https://dev.starliner.app}
      AUTH_DATABASE_URL: ${AUTH_DATABASE_URL:-postgres://postgres:postgres@auth-db:5432/auth_db}
      SERVER_BASE_URL: ${SERVER_BASE_URL:-server-api:9090}
      SERVER_BASIC_AUTH_USER: ${SERVER_BASIC_AUTH_USER:-test}
      SERVER_BASIC_AUTH_PASSWORD: ${SERVER_BASIC_AUTH_PASSWORD:-test}
    volumes:
      - ./client:/app
      - node-modules-client:/app/node_modules
    networks:
      - internal

  server-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/server/api/Dockerfile
      target: dev
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
    ports:
      - "9090:9090"
      - "40000:40000"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-main}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER:-test}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD:-test}
      CLUSTER_GRPC_ENDPOINT: ${CLUSTER_GRPC_ENDPOINT:-server-cluster:57400}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:-http://s3:8333}
      NATS_URL: ${NATS_URL:-http://nats:4222}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-access-key-123}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-secret-key-123}
      ENCRYPTION_KEY_BASE64: ${ENCRYPTION_KEY_BASE64:-D8gwlwA/vul5rfmnMeMI0Y5bdbZHYQhyTsOlvpk4RaI=}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}
    volumes:
      - ./server:/app
    networks:
      - internal

  server-builder:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/server/builder/Dockerfile
      target: dev
    depends_on:
      s3:
        condition: service_healthy
    ports:
      - "40001:40001"
    environment:
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:-http://s3:8333}
      NATS_URL: ${NATS_URL:-http://nats:4222}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-access-key-123}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-secret-key-123}
      IMAGE_REGISTRY_URL: ${IMAGE_REGISTRY_URL:-registry.staging.starliner.app}
      _EXPERIMENTAL_DAGGER_RUNNER_HOST: ${_EXPERIMENTAL_DAGGER_RUNNER_HOST:-tcp://dagger:1234}
    volumes:
      - ./server:/app
    networks:
      - internal

  server-cluster:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/server/cluster/Dockerfile
      target: dev
    ports:
      - "40002:40002"
      - "57400:57400"
    environment:
      NATS_URL: ${NATS_URL:-http://nats:4222}
      ENCRYPTION_KEY_BASE64: ${ENCRYPTION_KEY_BASE64:-D8gwlwA/vul5rfmnMeMI0Y5bdbZHYQhyTsOlvpk4RaI=}
    volumes:
      - ./server:/app
    networks:
      - internal

  server-provisioner:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/server/provisioner/Dockerfile
      target: dev
    ports:
      - "40003:40003"
    environment:
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:-http://s3:8333}
      NATS_URL: ${NATS_URL:-http://nats:4222}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-access-key-123}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-secret-key-123}
      ENCRYPTION_KEY_BASE64: ${ENCRYPTION_KEY_BASE64:-D8gwlwA/vul5rfmnMeMI0Y5bdbZHYQhyTsOlvpk4RaI=}
      PULUMI_BACKEND_URL: ${PULUMI_BACKEND_URL:-s3://pulumi-backend?endpoint=s3:8333&region=none&disableSSL=true&s3ForcePathStyle=true}
      PULUMI_CONFIG_PASSPHRASE: ${PULUMI_CONFIG_PASSPHRASE:-test}
    volumes:
      - ./server:/app
    networks:
      - internal

  db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-main}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d main'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

  auth-db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${AUTH_POSTGRES_DB:-auth_db}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d auth_db'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - internal

  nats:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/nats/Dockerfile
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data/jetstream
    command: ["-c", "/etc/nats/nats.conf"]
    networks:
      - internal

  nats-box:
    restart: unless-stopped
    build:
      context: .docker/nats-box
      dockerfile: Dockerfile
    depends_on:
      - nats
    entrypoint: /bin/sh
    tty: true
    networks:
      - internal

  master:
    build:
      context: .
      dockerfile: .docker/seaweedfs/Dockerfile
    ports:
      - "9333:9333"
      - "19333:19333"
    command: "-v=1 master -volumeSizeLimitMB 100 -resumeState=false -ip=master -ip.bind=0.0.0.0 -port=9333 -mdir=/var/lib/seaweedfs/master"
    volumes:
      - .docker/seaweedfs/data/master:/var/lib/seaweedfs/master
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9333 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - internal

  volume1:
    build:
      context: .
      dockerfile: .docker/seaweedfs/Dockerfile
    ports:
      - "8081:8081"
      - "18080:18080"
    command: 'volume -dataCenter=dc1 -rack=v1 -mserver="master:9333" -port=8081 -preStopSeconds=1 -dir=/var/lib/seaweedfs/volume1'
    volumes:
      - .docker/seaweedfs/data/volume1:/var/lib/seaweedfs/volume1
    depends_on:
      master:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://volume1:8081/status || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - internal

  volume2:
    build:
      context: .
      dockerfile: .docker/seaweedfs/Dockerfile
    ports:
      - "8082:8082"
      - "18082:18082"
    command: 'volume -dataCenter=dc2 -rack=v2 -mserver="master:9333" -port=8082 -preStopSeconds=1 -dir=/var/lib/seaweedfs/volume2'
    volumes:
      - .docker/seaweedfs/data/volume2:/var/lib/seaweedfs/volume2
    depends_on:
      master:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://volume2:8082/status || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - internal

  filer:
    build:
      context: .
      dockerfile: .docker/seaweedfs/Dockerfile
    ports:
      - "8888:8888"
      - "18888:18888"
    command: 'filer -defaultReplicaPlacement=100 -iam -master="master:9333"'
    volumes:
      - .docker/seaweedfs/data/filer:/data
    depends_on:
      volume1:
        condition: service_healthy
      volume2:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8888 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - internal

  s3:
    build:
      context: .
      dockerfile: .docker/seaweedfs/Dockerfile
    ports:
      - "8333:8333"
    command: '-v=9 s3 -filer="filer:8888" -ip.bind=0.0.0.0'
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-access-key-123}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-secret-key-123}
    depends_on:
      filer:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8333/status || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - internal

  # Fully qualified hostname necessary, so Dagger’s internal DNS can resolve it
  # See: https://github.com/dagger/dagger/issues/9439#issuecomment-3656217482
  registry.dev:
    build:
      context: .
      dockerfile: .docker/registry/Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registry-data:/data
    networks:
      - internal

  dagger:
    build:
      context: .
      dockerfile: .docker/dagger/Dockerfile
    privileged: true
    restart: unless-stopped
    volumes:
      - dagger-data:/var/lib/dagger
    networks:
      - internal

volumes:
  node-modules-client:
  auth-db-data:
  db-data:
  nats-data:
  registry-data:
  dagger-data:

networks:
  internal: