name: starliner

services:
  nats-exporter:
    restart: unless-stopped
    build:
      context: .docker/nats-exporter
      dockerfile: Dockerfile
    depends_on:
      - nats
    command:
      - "-varz"
      - "-connz"
      - "-routez"
      - "-gatewayz"
      - "-leafz"
      - "-accstatz"
      - "-jsz=all"
      - "-healthz"
      - "http://nats:8222"
    ports:
      - "7777:7777"
    networks:
      - internal

  prometheus:
    restart: unless-stopped
    build:
      context: .docker/prometheus
      dockerfile: Dockerfile
    ports:
      - "9091:9090"
    volumes:
      - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - internal

  grafana:
    restart: unless-stopped
    build:
      context: .docker/grafana
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./.docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./.docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - internal

volumes:
  prometheus-data:
  grafana-data:

networks:
  internal: