// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.5
// source: internal/core/infrastructure/nats/proto/v1/cluster.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cluster struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationName string                 `protobuf:"bytes,3,opt,name=organizationName,proto3" json:"organizationName,omitempty"`
	ProvisioningId   string                 `protobuf:"bytes,4,opt,name=provisioningId,proto3" json:"provisioningId,omitempty"`
	Ipv4Address      string                 `protobuf:"bytes,5,opt,name=ipv4Address,proto3" json:"ipv4Address,omitempty"`
	PublicKey        string                 `protobuf:"bytes,6,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey       string                 `protobuf:"bytes,7,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	KubeconfigBase64 string                 `protobuf:"bytes,8,opt,name=kubeconfigBase64,proto3" json:"kubeconfigBase64,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_internal_core_infrastructure_nats_proto_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_infrastructure_nats_proto_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *Cluster) GetProvisioningId() string {
	if x != nil {
		return x.ProvisioningId
	}
	return ""
}

func (x *Cluster) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *Cluster) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Cluster) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Cluster) GetKubeconfigBase64() string {
	if x != nil {
		return x.KubeconfigBase64
	}
	return ""
}

var File_internal_core_infrastructure_nats_proto_v1_cluster_proto protoreflect.FileDescriptor

const file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"8internal/core/infrastructure/nats/proto/v1/cluster.proto\x12\bproto.v1\"\x8d\x02\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x10organizationName\x18\x03 \x01(\tR\x10organizationName\x12&\n" +
	"\x0eprovisioningId\x18\x04 \x01(\tR\x0eprovisioningId\x12 \n" +
	"\vipv4Address\x18\x05 \x01(\tR\vipv4Address\x12\x1c\n" +
	"\tpublicKey\x18\x06 \x01(\tR\tpublicKey\x12\x1e\n" +
	"\n" +
	"privateKey\x18\a \x01(\tR\n" +
	"privateKey\x12*\n" +
	"\x10kubeconfigBase64\x18\b \x01(\tR\x10kubeconfigBase64B\x18Z\x16starliner.app/proto/v1b\x06proto3"

var (
	file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDescOnce sync.Once
	file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDescData []byte
)

func file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDescGZIP() []byte {
	file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDescOnce.Do(func() {
		file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDesc), len(file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDesc)))
	})
	return file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDescData
}

var file_internal_core_infrastructure_nats_proto_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_core_infrastructure_nats_proto_v1_cluster_proto_goTypes = []any{
	(*Cluster)(nil), // 0: proto.v1.Cluster
}
var file_internal_core_infrastructure_nats_proto_v1_cluster_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_core_infrastructure_nats_proto_v1_cluster_proto_init() }
func file_internal_core_infrastructure_nats_proto_v1_cluster_proto_init() {
	if File_internal_core_infrastructure_nats_proto_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDesc), len(file_internal_core_infrastructure_nats_proto_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_core_infrastructure_nats_proto_v1_cluster_proto_goTypes,
		DependencyIndexes: file_internal_core_infrastructure_nats_proto_v1_cluster_proto_depIdxs,
		MessageInfos:      file_internal_core_infrastructure_nats_proto_v1_cluster_proto_msgTypes,
	}.Build()
	File_internal_core_infrastructure_nats_proto_v1_cluster_proto = out.File
	file_internal_core_infrastructure_nats_proto_v1_cluster_proto_goTypes = nil
	file_internal_core_infrastructure_nats_proto_v1_cluster_proto_depIdxs = nil
}
