// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"starliner.app/pkg/api"
	"starliner.app/pkg/api/handler"
	"starliner.app/pkg/api/middleware"
	"starliner.app/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.Server, error) {
	rootHandler := handler.NewRootHandler()
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware(cfg)
	server := http.NewServer(rootHandler, basicAuthMiddleware)
	return server, nil
}
