// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"starliner.app/pkg/api"
	"starliner.app/pkg/api/handler"
	"starliner.app/pkg/api/middleware"
	"starliner.app/pkg/config"
	"starliner.app/pkg/db"
	"starliner.app/pkg/db/sqlc"
	"starliner.app/pkg/repository"
	"starliner.app/pkg/service"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config) (*http.Server, error) {
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware(cfg)
	sqlDB, err := db.Connect(cfg)
	if err != nil {
		return nil, err
	}
	queries := ProvideQueries(sqlDB)
	userRepository := repository.NewUserRepository(queries)
	userService := service.NewUserService(userRepository)
	userMiddleware := middleware.NewUserMiddleware(userService)
	rootHandler := handler.NewRootHandler()
	userHandler := handler.NewUserHandler()
	organizationRepository := repository.NewOrganizationRepository(queries)
	organizationService := service.NewOrganizationService(organizationRepository)
	organizationHandler := handler.NewOrganizationHandler(organizationService)
	projectRepository := repository.NewProjectRepository(queries)
	environmentRepository := repository.NewEnvironmentRepository(queries)
	projectService := service.NewProjectService(organizationService, projectRepository, organizationRepository, environmentRepository)
	projectHandler := handler.NewProjectHandler(projectService)
	environmentService := service.NewEnvironmentService(environmentRepository, organizationService)
	environmentHandler := handler.NewEnvironmentHandler(environmentService)
	server := http.NewServer(basicAuthMiddleware, userMiddleware, rootHandler, userHandler, organizationHandler, projectHandler, environmentHandler)
	return server, nil
}

// wire.go:

func ProvideQueries(db2 *sql.DB) *sqlc.Queries {
	return sqlc.New(db2)
}
