global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: nats
    static_configs:
      - targets: ["nats-exporter:7777"]

  - job_name: nats-surveyor
    static_configs:
      - targets: ["nats-surveyor:7777"]

#  - job_name: server-api
#    static_configs:
#      - targets: ["server-api:9090"]
#
#  - job_name: server-builder
#    static_configs:
#      - targets: ["server-builder:57500"]
#
#  - job_name: server-cluster
#    static_configs:
#      - targets: ["server-cluster:57400"]
#
#  - job_name: server-provisioner
#    static_configs:
#      - targets: ["server-provisioner:40003"]
#
