// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "tags": [
                    "root"
                ],
                "summary": "Get root",
                "operationId": "getRoot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Root"
                        }
                    }
                }
            }
        },
        "/builds/{id}/logs": {
            "get": {
                "tags": [
                    "build"
                ],
                "summary": "Get Build Logs",
                "operationId": "getBuildLogs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Build ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BuildLogs"
                        }
                    }
                }
            }
        },
        "/clusters": {
            "post": {
                "tags": [
                    "cluster"
                ],
                "summary": "Create Cluster",
                "operationId": "createCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Cluster",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateCluster"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Cluster"
                        }
                    }
                }
            }
        },
        "/clusters/{id}": {
            "get": {
                "tags": [
                    "cluster"
                ],
                "summary": "Get Cluster",
                "operationId": "getCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Cluster ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Cluster"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "cluster"
                ],
                "summary": "Delete Cluster",
                "operationId": "deleteCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Cluster ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/clusters/{id}/private-key": {
            "get": {
                "tags": [
                    "cluster"
                ],
                "summary": "Get Cluster Private Key",
                "operationId": "getClusterPrivateKey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Cluster ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/deployments/databases": {
            "post": {
                "tags": [
                    "deployment"
                ],
                "summary": "Deploy database",
                "operationId": "deployDatabase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Deploy Database",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeployDatabase"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/git": {
            "post": {
                "tags": [
                    "deployment"
                ],
                "summary": "Deploy from Git Repository",
                "operationId": "deployFromGitRepository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Deploy from Git",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeployFromGit"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/git/{deploymentId}": {
            "put": {
                "tags": [
                    "deployment"
                ],
                "summary": "Update Deploy from Git",
                "operationId": "updateDeployFromGitRepository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Deployment ID",
                        "name": "deploymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Deploy from Git",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateDeployFromGit"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/images": {
            "post": {
                "tags": [
                    "deployment"
                ],
                "summary": "Deploy image",
                "operationId": "deployImage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Deploy Image",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeployImage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/images/{deploymentId}": {
            "put": {
                "tags": [
                    "deployment"
                ],
                "summary": "Update image deployment",
                "operationId": "updateImageDeployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Deployment ID",
                        "name": "deploymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Image",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateImage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/ingresses": {
            "post": {
                "tags": [
                    "deployment"
                ],
                "summary": "Deploy ingress",
                "operationId": "deployIngress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Deploy Ingress",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeployIngress"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/ingresses/{deploymentId}": {
            "put": {
                "tags": [
                    "deployment"
                ],
                "summary": "Update ingress deployment",
                "operationId": "updateIngressDeployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Deployment ID",
                        "name": "deploymentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Ingress",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateIngress"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/{id}": {
            "delete": {
                "tags": [
                    "deployment"
                ],
                "summary": "Delete deployment",
                "operationId": "deleteDeployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/{id}/logs": {
            "get": {
                "tags": [
                    "deployment"
                ],
                "summary": "Stream deployment logs",
                "operationId": "streamDeploymentLogs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {
                            "Cache-Control": {
                                "type": "string",
                                "description": "no-cache"
                            },
                            "Connection": {
                                "type": "string",
                                "description": "keep-alive"
                            },
                            "Content-Type": {
                                "type": "string",
                                "description": "text/event-stream"
                            }
                        }
                    }
                }
            }
        },
        "/environments": {
            "post": {
                "tags": [
                    "environment"
                ],
                "summary": "Create Environment",
                "operationId": "createEnvironment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Environment",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateEnvironment"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/environments/{id}/builds": {
            "get": {
                "tags": [
                    "environment"
                ],
                "summary": "Get Environment Builds",
                "operationId": "getEnvironmentBuilds",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Environment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.GitDeploymentBuild"
                            }
                        }
                    }
                }
            }
        },
        "/environments/{id}/deployments": {
            "get": {
                "tags": [
                    "environment"
                ],
                "summary": "Get Environment Deployments",
                "operationId": "getEnvironmentDeployments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Environment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Deployments"
                        }
                    }
                }
            }
        },
        "/invites/accept": {
            "post": {
                "tags": [
                    "organization"
                ],
                "summary": "Accept organization invite",
                "operationId": "acceptOrganizationInvite",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Accept Invite",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AcceptInvite"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/invites/{inviteId}": {
            "get": {
                "tags": [
                    "organization"
                ],
                "summary": "Get organization invite details",
                "operationId": "getOrganizationInviteDetails",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Invite ID",
                        "name": "inviteId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.OrganizationInvite"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "Get current user",
                "operationId": "getUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.User"
                        }
                    }
                }
            }
        },
        "/organizations": {
            "get": {
                "tags": [
                    "organization"
                ],
                "summary": "Get user organizations",
                "operationId": "getUserOrganizations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Organization"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "organization"
                ],
                "summary": "Create organization",
                "operationId": "createOrganization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Organization",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateOrganization"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Organization"
                        }
                    }
                }
            }
        },
        "/organizations/{id}/clusters": {
            "get": {
                "tags": [
                    "organization"
                ],
                "summary": "Get Organization Clusters",
                "operationId": "getOrganizationClusters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Cluster"
                            }
                        }
                    }
                }
            }
        },
        "/organizations/{id}/invites": {
            "post": {
                "tags": [
                    "organization"
                ],
                "summary": "Create organization invite",
                "operationId": "createOrganizationInvite",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.OrganizationInvite"
                        }
                    }
                }
            }
        },
        "/organizations/{id}/projects": {
            "get": {
                "tags": [
                    "organization"
                ],
                "summary": "Get Organization Projects",
                "operationId": "getUserProjects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Project"
                            }
                        }
                    }
                }
            }
        },
        "/organizations/{id}/settings/credential/hetzner": {
            "get": {
                "tags": [
                    "organization"
                ],
                "summary": "Get Hetzner Provisioning Credential",
                "operationId": "getHetznerCredential",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetOrganizationProvisioningCredentialResponse"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "organization"
                ],
                "summary": "Upsert Hetzner Provisioning Credential",
                "operationId": "upsertHetznerCredential",
                "parameters": [
                    {
                        "description": "Upsert Hetzner Credential",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpsertHetznerCredential"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/projects": {
            "post": {
                "tags": [
                    "project"
                ],
                "summary": "Create Project",
                "operationId": "createProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Project",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Project"
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "get": {
                "tags": [
                    "project"
                ],
                "summary": "Get Project",
                "operationId": "getProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Project"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "project"
                ],
                "summary": "Delete Project",
                "operationId": "deleteProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/projects/{id}/cluster": {
            "get": {
                "tags": [
                    "project"
                ],
                "summary": "Get Project Cluster",
                "operationId": "getProjectCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ProjectCluster"
                        }
                    }
                }
            }
        },
        "/projects/{id}/environments": {
            "get": {
                "tags": [
                    "project"
                ],
                "summary": "Get Project Environments",
                "operationId": "getProjectEnvironments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Environment"
                            }
                        }
                    }
                }
            }
        },
        "/teams/{organizationId}": {
            "get": {
                "tags": [
                    "team"
                ],
                "summary": "Get User Teams",
                "operationId": "getUserTeams",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Team"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "team"
                ],
                "summary": "Create team",
                "operationId": "createTeam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Team",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateTeam"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Team"
                        }
                    }
                }
            }
        },
        "/teams/{organizationId}/join": {
            "post": {
                "tags": [
                    "team"
                ],
                "summary": "Join a team by slug",
                "operationId": "joinTeam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Join Team",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.JoinTeam"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/teams/{organizationId}/{teamId}/members": {
            "get": {
                "tags": [
                    "team"
                ],
                "summary": "Get Team Members",
                "operationId": "getTeamMembers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "team"
                ],
                "summary": "Add current user to team",
                "operationId": "addTeamMember",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "delete": {
                "tags": [
                    "team"
                ],
                "summary": "Remove Team Member",
                "operationId": "removeTeamMember",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "request.AcceptInvite": {
            "type": "object",
            "required": [
                "inviteId"
            ],
            "properties": {
                "inviteId": {
                    "type": "string"
                }
            }
        },
        "request.CreateCluster": {
            "type": "object",
            "required": [
                "name",
                "organizationId",
                "serverType"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "integer"
                },
                "serverType": {
                    "type": "string",
                    "enum": [
                        "cx23",
                        "ccx33"
                    ]
                }
            }
        },
        "request.CreateEnvironment": {
            "type": "object",
            "required": [
                "name",
                "organization_id",
                "project_id"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "integer"
                },
                "project_id": {
                    "type": "integer"
                }
            }
        },
        "request.CreateOrganization": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "request.CreateProject": {
            "type": "object",
            "required": [
                "cluster_id",
                "name",
                "organization_id",
                "team_id"
            ],
            "properties": {
                "cluster_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "integer"
                },
                "team_id": {
                    "type": "integer"
                }
            }
        },
        "request.CreateTeam": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "request.DeployDatabase": {
            "type": "object",
            "required": [
                "environmentId",
                "serviceName"
            ],
            "properties": {
                "environmentId": {
                    "type": "integer"
                },
                "serviceName": {
                    "type": "string"
                }
            }
        },
        "request.DeployFromGit": {
            "type": "object",
            "required": [
                "dockerfilePath",
                "environmentId",
                "envs",
                "gitUrl",
                "port",
                "projectRepositoryPath",
                "serviceName"
            ],
            "properties": {
                "dockerfilePath": {
                    "type": "string"
                },
                "environmentId": {
                    "type": "integer"
                },
                "envs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EnvVar"
                    }
                },
                "gitUrl": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "projectRepositoryPath": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                }
            }
        },
        "request.DeployImage": {
            "type": "object",
            "required": [
                "environmentId",
                "envs",
                "imageName",
                "port",
                "serviceName",
                "tag"
            ],
            "properties": {
                "environmentId": {
                    "type": "integer"
                },
                "envs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EnvVar"
                    }
                },
                "imageName": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "serviceName": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "request.DeployIngress": {
            "type": "object",
            "required": [
                "environmentId",
                "ingressHosts"
            ],
            "properties": {
                "environmentId": {
                    "type": "integer"
                },
                "ingressHosts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.IngressHost"
                    }
                }
            }
        },
        "request.EnvVar": {
            "type": "object",
            "required": [
                "name",
                "value"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "request.IngressHost": {
            "type": "object",
            "required": [
                "host",
                "paths"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "paths": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.IngressPath"
                    }
                }
            }
        },
        "request.IngressPath": {
            "type": "object",
            "required": [
                "path",
                "pathType",
                "serviceName"
            ],
            "properties": {
                "path": {
                    "type": "string"
                },
                "pathType": {
                    "type": "string",
                    "enum": [
                        "Prefix",
                        "Exact"
                    ]
                },
                "serviceName": {
                    "type": "string"
                }
            }
        },
        "request.JoinTeam": {
            "type": "object",
            "required": [
                "slug"
            ],
            "properties": {
                "slug": {
                    "type": "string"
                }
            }
        },
        "request.UpdateDeployFromGit": {
            "type": "object",
            "required": [
                "dockerfilePath",
                "environmentId",
                "envs",
                "port",
                "projectRepositoryPath"
            ],
            "properties": {
                "dockerfilePath": {
                    "type": "string"
                },
                "environmentId": {
                    "type": "integer"
                },
                "envs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EnvVar"
                    }
                },
                "port": {
                    "type": "integer"
                },
                "projectRepositoryPath": {
                    "type": "string"
                }
            }
        },
        "request.UpdateImage": {
            "type": "object",
            "required": [
                "environmentId",
                "envs",
                "imageName",
                "port",
                "tag"
            ],
            "properties": {
                "environmentId": {
                    "type": "integer"
                },
                "envs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EnvVar"
                    }
                },
                "imageName": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "request.UpdateIngress": {
            "type": "object",
            "required": [
                "environmentId",
                "ingressHosts"
            ],
            "properties": {
                "environmentId": {
                    "type": "integer"
                },
                "ingressHosts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.IngressHost"
                    }
                }
            }
        },
        "request.UpsertHetznerCredential": {
            "type": "object",
            "required": [
                "apiKey"
            ],
            "properties": {
                "apiKey": {
                    "type": "string"
                }
            }
        },
        "response.BuildLogs": {
            "type": "object",
            "required": [
                "logs"
            ],
            "properties": {
                "logs": {
                    "type": "string"
                }
            }
        },
        "response.Cluster": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "ipv4Address",
                "name",
                "organizationId",
                "serverType",
                "status"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ipv4Address": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "integer"
                },
                "serverType": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "pending",
                        "running",
                        "deleted"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.ClusterStatus"
                        }
                    ]
                }
            }
        },
        "response.ClusterStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "deleted"
            ],
            "x-enum-varnames": [
                "ClusterStatusPending",
                "ClusterStatusRunning",
                "ClusterStatusDeleted"
            ]
        },
        "response.DatabaseDeployment": {
            "type": "object",
            "required": [
                "database",
                "id",
                "internalEndpoint",
                "password",
                "port",
                "serviceName",
                "status",
                "username"
            ],
            "properties": {
                "database": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "internalEndpoint": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.Deployments": {
            "type": "object",
            "required": [
                "databases",
                "gitDeployments",
                "images",
                "ingresses"
            ],
            "properties": {
                "databases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.DatabaseDeployment"
                    }
                },
                "gitDeployments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.GitDeployment"
                    }
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ImageDeployment"
                    }
                },
                "ingresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.IngressDeployment"
                    }
                }
            }
        },
        "response.EnvVar": {
            "type": "object",
            "required": [
                "name",
                "value"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "response.Environment": {
            "type": "object",
            "required": [
                "id",
                "name",
                "slug"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "response.GetOrganizationProvisioningCredentialResponse": {
            "type": "object",
            "properties": {
                "credential": {
                    "$ref": "#/definitions/response.OrganizationProvisioningCredential"
                }
            }
        },
        "response.GitDeployment": {
            "type": "object",
            "required": [
                "dockerfilePath",
                "envVars",
                "gitUrl",
                "id",
                "internalEndpoint",
                "port",
                "projectRepositoryPath",
                "serviceName",
                "status"
            ],
            "properties": {
                "dockerfilePath": {
                    "type": "string"
                },
                "envVars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EnvVar"
                    }
                },
                "gitUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "internalEndpoint": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "projectRepositoryPath": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.GitDeploymentBuild": {
            "type": "object",
            "required": [
                "buildId",
                "createdAt",
                "deploymentId",
                "deploymentName",
                "dockerfilePath",
                "gitUrl",
                "projectPath",
                "status"
            ],
            "properties": {
                "buildId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deploymentId": {
                    "type": "integer"
                },
                "deploymentName": {
                    "type": "string"
                },
                "dockerfilePath": {
                    "type": "string"
                },
                "gitUrl": {
                    "type": "string"
                },
                "projectPath": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.ImageDeployment": {
            "type": "object",
            "required": [
                "envVars",
                "id",
                "imageName",
                "internalEndpoint",
                "port",
                "serviceName",
                "status",
                "tag"
            ],
            "properties": {
                "envVars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EnvVar"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "imageName": {
                    "type": "string"
                },
                "internalEndpoint": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "response.IngressDeployment": {
            "type": "object",
            "required": [
                "hosts",
                "id",
                "port",
                "serviceName",
                "status"
            ],
            "properties": {
                "hosts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.IngressHost"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "port": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.IngressHost": {
            "type": "object",
            "required": [
                "host",
                "paths"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "paths": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.IngressPath"
                    }
                }
            }
        },
        "response.IngressPath": {
            "type": "object",
            "required": [
                "path",
                "pathType",
                "serviceName"
            ],
            "properties": {
                "path": {
                    "type": "string"
                },
                "pathType": {
                    "type": "string",
                    "enum": [
                        "Prefix",
                        "Exact"
                    ]
                },
                "serviceName": {
                    "type": "string"
                }
            }
        },
        "response.Organization": {
            "type": "object",
            "required": [
                "id",
                "name",
                "owner_id",
                "slug"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "response.OrganizationInvite": {
            "type": "object",
            "required": [
                "created_at",
                "expires_at",
                "id",
                "organization_id",
                "organization_name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "integer"
                },
                "organization_name": {
                    "type": "string"
                }
            }
        },
        "response.OrganizationProvisioningCredential": {
            "type": "object",
            "required": [
                "provider",
                "secret"
            ],
            "properties": {
                "provider": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "response.Project": {
            "type": "object",
            "required": [
                "clusterId",
                "createdAt",
                "environments",
                "id",
                "name"
            ],
            "properties": {
                "clusterId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "environments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Environment"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.ProjectCluster": {
            "type": "object",
            "required": [
                "clusterId",
                "clusterName"
            ],
            "properties": {
                "clusterId": {
                    "type": "integer"
                },
                "clusterName": {
                    "type": "string"
                }
            }
        },
        "response.Root": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.Team": {
            "type": "object",
            "required": [
                "id",
                "name",
                "organization_id",
                "slug"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "response.User": {
            "type": "object",
            "required": [
                "better_auth_id",
                "user_id"
            ],
            "properties": {
                "better_auth_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Starliner API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
