definitions:
  request.CreateCluster:
    properties:
      name:
        type: string
      organizationId:
        type: integer
    required:
    - name
    - organizationId
    type: object
  request.CreateEnvironment:
    properties:
      name:
        type: string
      organization_id:
        type: integer
      project_id:
        type: integer
    required:
    - name
    - organization_id
    - project_id
    type: object
  request.CreateOrganization:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  request.CreateProject:
    properties:
      cluster_id:
        type: integer
      name:
        type: string
      organization_id:
        type: integer
    required:
    - cluster_id
    - name
    - organization_id
    type: object
  request.Database:
    enum:
    - postgres
    type: string
    x-enum-varnames:
    - Postgres
  request.DeployDatabase:
    properties:
      database:
        allOf:
        - $ref: '#/definitions/request.Database'
        enum:
        - postgres
      environmentId:
        type: integer
    required:
    - database
    - environmentId
    type: object
  request.DeployImage:
    properties:
      environmentId:
        type: integer
      envs:
        items:
          $ref: '#/definitions/request.EnvVar'
        type: array
      imageName:
        type: string
      port:
        type: integer
      serviceName:
        type: string
      tag:
        type: string
    required:
    - environmentId
    - envs
    - imageName
    - port
    - serviceName
    - tag
    type: object
  request.DeployIngress:
    properties:
      environmentId:
        type: integer
      ingressHosts:
        items:
          $ref: '#/definitions/request.IngressHost'
        type: array
    required:
    - environmentId
    - ingressHosts
    type: object
  request.EnvVar:
    properties:
      name:
        type: string
      value:
        type: string
    required:
    - name
    - value
    type: object
  request.IngressHost:
    properties:
      host:
        type: string
      paths:
        items:
          $ref: '#/definitions/request.IngressPath'
        type: array
    required:
    - host
    - paths
    type: object
  request.IngressPath:
    properties:
      path:
        type: string
      pathType:
        enum:
        - Prefix
        - Exact
        type: string
      serviceName:
        type: string
    required:
    - path
    - pathType
    - serviceName
    type: object
  response.Cluster:
    properties:
      id:
        type: integer
      ipv4Address:
        type: string
      name:
        type: string
      organizationId:
        type: integer
      status:
        allOf:
        - $ref: '#/definitions/response.ClusterStatus'
        enum:
        - pending
        - running
        - deleted
    required:
    - id
    - ipv4Address
    - name
    - organizationId
    - status
    type: object
  response.ClusterStatus:
    enum:
    - pending
    - running
    - deleted
    type: string
    x-enum-varnames:
    - ClusterStatusPending
    - ClusterStatusRunning
    - ClusterStatusDeleted
  response.DatabaseDeployment:
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      port:
        type: string
      status:
        type: string
      username:
        type: string
    required:
    - id
    - name
    - password
    - port
    - status
    - username
    type: object
  response.Deployments:
    properties:
      databases:
        items:
          $ref: '#/definitions/response.DatabaseDeployment'
        type: array
      images:
        items:
          $ref: '#/definitions/response.ImageDeployment'
        type: array
      ingresses:
        items:
          $ref: '#/definitions/response.IngressDeployment'
        type: array
    required:
    - databases
    - images
    - ingresses
    type: object
  response.Environment:
    properties:
      id:
        type: integer
      name:
        type: string
      slug:
        type: string
    required:
    - id
    - name
    - slug
    type: object
  response.ImageDeployment:
    properties:
      id:
        type: integer
      imageName:
        type: string
      port:
        type: string
      serviceName:
        type: string
      status:
        type: string
      tag:
        type: string
    required:
    - id
    - imageName
    - port
    - serviceName
    - status
    - tag
    type: object
  response.IngressDeployment:
    properties:
      hosts:
        items:
          $ref: '#/definitions/response.IngressHost'
        type: array
      id:
        type: integer
      port:
        type: string
      serviceName:
        type: string
      status:
        type: string
    required:
    - hosts
    - id
    - port
    - serviceName
    - status
    type: object
  response.IngressHost:
    properties:
      host:
        type: string
      paths:
        items:
          $ref: '#/definitions/response.IngressPath'
        type: array
    required:
    - host
    - paths
    type: object
  response.IngressPath:
    properties:
      path:
        type: string
      pathType:
        enum:
        - Prefix
        - Exact
        type: string
      serviceName:
        type: string
    required:
    - path
    - pathType
    - serviceName
    type: object
  response.Organization:
    properties:
      id:
        type: integer
      name:
        type: string
      owner_id:
        type: integer
      slug:
        type: string
    required:
    - id
    - name
    - owner_id
    - slug
    type: object
  response.Project:
    properties:
      clusterId:
        type: integer
      environments:
        items:
          $ref: '#/definitions/response.Environment'
        type: array
      id:
        type: integer
      name:
        type: string
    required:
    - clusterId
    - environments
    - id
    - name
    type: object
  response.Root:
    properties:
      message:
        type: string
    required:
    - message
    type: object
  response.User:
    properties:
      better_auth_id:
        type: string
      user_id:
        type: integer
    required:
    - better_auth_id
    - user_id
    type: object
info:
  contact: {}
  title: Starliner API
  version: "1.0"
paths:
  /:
    get:
      operationId: getRoot
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Root'
      summary: Get root
      tags:
      - root
  /builds:
    post:
      operationId: triggerBuild
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Trigger Build
      tags:
      - build
  /clusters:
    post:
      operationId: createCluster
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create Cluster
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateCluster'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Cluster'
      summary: Create Cluster
      tags:
      - cluster
  /clusters/{id}:
    delete:
      operationId: deleteCluster
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete Cluster
      tags:
      - cluster
    get:
      operationId: getCluster
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Cluster'
      summary: Get Cluster
      tags:
      - cluster
  /clusters/{id}/private-key:
    get:
      operationId: getClusterPrivateKey
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Get Cluster Private Name
      tags:
      - cluster
  /deployments/{id}:
    delete:
      operationId: deleteDeployment
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Deployment ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete deployment
      tags:
      - deployment
  /deployments/databases:
    post:
      operationId: deployDatabase
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Deploy Database
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DeployDatabase'
      responses:
        "200":
          description: OK
      summary: Deploy database
      tags:
      - deployment
  /deployments/images:
    post:
      operationId: deployImage
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Deploy Image
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DeployImage'
      responses:
        "200":
          description: OK
      summary: Deploy image
      tags:
      - deployment
  /deployments/ingresses:
    post:
      operationId: deployIngress
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Deploy Ingress
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DeployIngress'
      responses:
        "200":
          description: OK
      summary: Deploy ingress
      tags:
      - deployment
  /environments:
    post:
      operationId: createEnvironment
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create Environment
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateEnvironment'
      responses:
        "201":
          description: Created
      summary: Create Environment
      tags:
      - environment
  /environments/{id}/deployments:
    get:
      operationId: getEnvironmentDeployments
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Environment ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Deployments'
      summary: Get Environment Deployments
      tags:
      - environment
  /me:
    get:
      operationId: getUser
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
      summary: Get current user
      tags:
      - user
  /organizations:
    get:
      operationId: getUserOrganizations
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Organization'
            type: array
      summary: Get user organizations
      tags:
      - organization
    post:
      operationId: createOrganization
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create Organization
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateOrganization'
      responses:
        "201":
          description: Created
      summary: Create organization
      tags:
      - organization
  /organizations/{id}/clusters:
    get:
      operationId: getOrganizationClusters
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Organization ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Cluster'
            type: array
      summary: Get Organization Clusters
      tags:
      - organization
  /organizations/{id}/projects:
    get:
      operationId: getOrganizationProjects
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Organization ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Project'
            type: array
      summary: Get Organization Projects
      tags:
      - organization
  /projects:
    post:
      operationId: createProject
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create Project
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateProject'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Project'
      summary: Create Project
      tags:
      - project
  /projects/{id}:
    delete:
      operationId: deleteProject
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete Project
      tags:
      - project
    get:
      operationId: getProject
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Project'
      summary: Get Project
      tags:
      - project
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
