definitions:
  handler.RootResponse:
    properties:
      message:
        type: string
    type: object
  handler.UserResponse:
    properties:
      better_auth_id:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
  title: Starliner API
  version: "1.0"
paths:
  /:
    get:
      operationId: GetRoot
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.RootResponse'
      summary: Get Root
      tags:
      - root
  /me:
    get:
      operationId: getUser
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UserResponse'
      summary: Get user
      tags:
      - user
swagger: "2.0"
