definitions:
  entity.ClusterStatus:
    enum:
    - pending
    - running
    - deleted
    type: string
    x-enum-varnames:
    - ClusterPending
    - ClusterRunning
    - ClusterDeleted
  request.CreateCluster:
    properties:
      name:
        type: string
      organizationId:
        type: integer
    required:
    - name
    - organizationId
    type: object
  request.CreateEnvironment:
    properties:
      name:
        type: string
      organization_id:
        type: integer
      project_id:
        type: integer
    required:
    - name
    - organization_id
    - project_id
    type: object
  request.CreateOrganization:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  request.CreateProject:
    properties:
      cluster_id:
        type: integer
      name:
        type: string
      organization_id:
        type: integer
    required:
    - cluster_id
    - name
    - organization_id
    type: object
  request.UpdateProjectName:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  response.Cluster:
    properties:
      id:
        type: integer
      ipv4Address:
        type: string
      name:
        type: string
      organizationId:
        type: integer
      status:
        allOf:
        - $ref: '#/definitions/entity.ClusterStatus'
        enum:
        - pending
        - running
        - deleted
    required:
    - id
    - ipv4Address
    - name
    - organizationId
    - status
    type: object
  response.Environment:
    properties:
      id:
        type: integer
      name:
        type: string
      slug:
        type: string
    required:
    - id
    - name
    - slug
    type: object
  response.Organization:
    properties:
      id:
        type: integer
      name:
        type: string
      owner_id:
        type: integer
      slug:
        type: string
    required:
    - id
    - name
    - owner_id
    - slug
    type: object
  response.Project:
    properties:
      clusterId:
        type: integer
      environments:
        items:
          $ref: '#/definitions/response.Environment'
        type: array
      id:
        type: integer
      name:
        type: string
    required:
    - clusterId
    - environments
    - id
    - name
    type: object
  response.Root:
    properties:
      message:
        type: string
    required:
    - message
    type: object
  response.User:
    properties:
      better_auth_id:
        type: string
      user_id:
        type: integer
    required:
    - better_auth_id
    - user_id
    type: object
info:
  contact: {}
  title: Starliner API
  version: "1.0"
paths:
  /:
    get:
      operationId: getRoot
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Root'
      summary: Get root
      tags:
      - root
  /builds:
    post:
      operationId: triggerBuild
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Trigger Build
      tags:
      - build
  /clusters:
    post:
      operationId: createCluster
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create Cluster
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateCluster'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Cluster'
      summary: Create Cluster
      tags:
      - cluster
  /clusters/{id}:
    delete:
      operationId: deleteCluster
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete Cluster
      tags:
      - cluster
    get:
      operationId: getCluster
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Cluster'
      summary: Get Cluster
      tags:
      - cluster
  /clusters/{id}/private-key:
    get:
      operationId: getClusterPrivateKey
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Get Cluster Private Key
      tags:
      - cluster
  /environments:
    post:
      operationId: createEnvironment
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create Environment
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateEnvironment'
      responses:
        "201":
          description: Created
      summary: Create Environment
      tags:
      - environment
  /me:
    get:
      operationId: getUser
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
      summary: Get current user
      tags:
      - user
  /organizations:
    get:
      operationId: getUserOrganizations
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Organization'
            type: array
      summary: Get user organizations
      tags:
      - organization
    post:
      operationId: createOrganization
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create Organization
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateOrganization'
      responses:
        "201":
          description: Created
      summary: Create organization
      tags:
      - organization
  /organizations/{id}/clusters:
    get:
      operationId: getOrganizationClusters
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Organization ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Cluster'
            type: array
      summary: Get Organization Clusters
      tags:
      - organization
  /organizations/{id}/projects:
    get:
      operationId: getOrganizationProjects
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Organization ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Project'
            type: array
      summary: Get Organization Projects
      tags:
      - organization
  /projects:
    post:
      operationId: createProject
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create Project
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateProject'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Project'
      summary: Create Project
      tags:
      - project
  /projects/{id}:
    delete:
      operationId: deleteProject
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete Project
      tags:
      - project
    get:
      operationId: getProject
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Project'
      summary: Get Project
      tags:
      - project
    put:
      operationId: updateProjectName
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Project Name
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateProjectName'
      responses:
        "200":
          description: OK
      summary: Update Project Name
      tags:
      - project
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
