{{- if .Values.cloudflare.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudflare-api-key
type: Opaque
stringData:
  apiKey: {{ .Values.cloudflare.apiKey | quote }}
{{- end }}