FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENTRYPOINT ["air", \
    "--build.cmd=go build -o build/server ./cmd/api/main.go", \
    "--build.bin=./build/server"]