// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package sqlc

import (
	"context"
)

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO deployments (
    name,
    environment_id
) VALUES (
    $1,
    $2
)
`

type CreateDeploymentParams struct {
	Name          string
	EnvironmentID int64
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment, arg.Name, arg.EnvironmentID)
	return err
}
