// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment.sql

package sqlc

import (
	"context"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (
    name,
    slug,
    project_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, slug, project_id, created_at, updated_at
`

type CreateEnvironmentParams struct {
	Name      string
	Slug      string
	ProjectID int64
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment, arg.Name, arg.Slug, arg.ProjectID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
