// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package sqlc

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name,
    slug,
    owner_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, slug, owner_id, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name    string
	Slug    string
	OwnerID int64
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization, arg.Name, arg.Slug, arg.OwnerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, owner_id, created_at, updated_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT id, name, slug, owner_id, created_at, updated_at
FROM organizations
WHERE owner_id = $1
`

func (q *Queries) GetUserOrganizations(ctx context.Context, ownerID int64) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrganizations, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
