definitions:
  request.SendResetPasswordRequest:
    properties:
      resetUrl:
        type: string
      to:
        type: string
    required:
    - resetUrl
    - to
    type: object
  request.SendVerificationEmailRequest:
    properties:
      to:
        type: string
      verificationUrl:
        type: string
    required:
    - to
    - verificationUrl
    type: object
  response.Root:
    properties:
      message:
        type: string
    required:
    - message
    type: object
info:
  contact: {}
  title: Starliner Auth API
  version: "1.0"
paths:
  /:
    get:
      operationId: getRoot
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Root'
      summary: Get root
      tags:
      - root
  /auth/send-reset-password:
    post:
      operationId: sendResetPassword
      parameters:
      - description: Password reset
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SendResetPasswordRequest'
      responses:
        "204":
          description: No Content
      summary: Send password reset email
      tags:
      - auth
  /auth/send-verification-email:
    post:
      operationId: sendVerificationEmail
      parameters:
      - description: Verification
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SendVerificationEmailRequest'
      responses:
        "204":
          description: No Content
      summary: Send email verification
      tags:
      - auth
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
