// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateauthAuth = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "tags": [
                    "root"
                ],
                "summary": "Get root",
                "operationId": "getRoot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Root"
                        }
                    }
                }
            }
        },
        "/auth/send-reset-password": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Send password reset email",
                "operationId": "sendResetPassword",
                "parameters": [
                    {
                        "description": "Password reset",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/send-verification-email": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Send email verification",
                "operationId": "sendVerificationEmail",
                "parameters": [
                    {
                        "description": "Verification",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendVerificationEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "request.SendResetPasswordRequest": {
            "type": "object",
            "required": [
                "resetUrl",
                "to"
            ],
            "properties": {
                "resetUrl": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "request.SendVerificationEmailRequest": {
            "type": "object",
            "required": [
                "to",
                "verificationUrl"
            ],
            "properties": {
                "to": {
                    "type": "string"
                },
                "verificationUrl": {
                    "type": "string"
                }
            }
        },
        "response.Root": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerAuthInfoauth holds exported Swagger Info so clients can modify it
var SwaggerAuthInfoauth = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Starliner Auth API",
	Description:      "",
	InfoInstanceName: "auth",
	SwaggerTemplate:  docTemplateauthAuth,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerAuthInfoauth.InstanceName(), SwaggerAuthInfoauth)
}
