apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-selector
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
  clusterIP: None

