ingress:
  hostnameAnnotation: ""
  tls:
    enabled: false
  rules:
    - host:
      paths:
        - path:
          pathType:
          service:
            name:
            port:
              number:
