// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: build.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (
    deployment_id
) VALUES (
    $1
)
RETURNING id, deployment_id, status, logs, created_at, updated_at
`

func (q *Queries) CreateBuild(ctx context.Context, deploymentID sql.NullInt64) (Build, error) {
	row := q.db.QueryRowContext(ctx, createBuild, deploymentID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Status,
		&i.Logs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuildLogs = `-- name: GetBuildLogs :one
SELECT
    b.logs
FROM builds b
INNER JOIN deployments d ON d.id = b.deployment_id
INNER JOIN environments e ON d.environment_id = e.id
INNER JOIN projects ON e.project_id = projects.id
INNER JOIN teams ON teams.id = projects.team_id
INNER JOIN team_members ON team_members.team_id = teams.id
WHERE b.id = $1
AND team_members.user_id = $2
`

type GetBuildLogsParams struct {
	BuildID int64
	UserID  int64
}

func (q *Queries) GetBuildLogs(ctx context.Context, arg GetBuildLogsParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getBuildLogs, arg.BuildID, arg.UserID)
	var logs sql.NullString
	err := row.Scan(&logs)
	return logs, err
}

const getEnvironmentGitDeploymentBuilds = `-- name: GetEnvironmentGitDeploymentBuilds :many
SELECT
    b.id as build_id,
    d.id as deployment_id,
    d.name as deployment_name,
    b.status,
    gd.url,
    gd.project_path,
    gd.dockerfile_path,
    b.created_at
FROM deployments d
INNER JOIN git_deployments gd ON gd.deployment_id = d.id
INNER JOIN builds b ON d.id = b.deployment_id
INNER JOIN environments e ON d.environment_id = e.id
WHERE environment_id = $1
ORDER BY b.created_at DESC
`

type GetEnvironmentGitDeploymentBuildsRow struct {
	BuildID        int64
	DeploymentID   int64
	DeploymentName string
	Status         BuildStatus
	Url            string
	ProjectPath    string
	DockerfilePath string
	CreatedAt      time.Time
}

func (q *Queries) GetEnvironmentGitDeploymentBuilds(ctx context.Context, environmentID int64) ([]GetEnvironmentGitDeploymentBuildsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnvironmentGitDeploymentBuilds, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnvironmentGitDeploymentBuildsRow
	for rows.Next() {
		var i GetEnvironmentGitDeploymentBuildsRow
		if err := rows.Scan(
			&i.BuildID,
			&i.DeploymentID,
			&i.DeploymentName,
			&i.Status,
			&i.Url,
			&i.ProjectPath,
			&i.DockerfilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuildInformation = `-- name: UpdateBuildInformation :exec
UPDATE builds
SET
    status = $1,
    logs = $2
WHERE id = $3
`

type UpdateBuildInformationParams struct {
	Status BuildStatus
	Logs   sql.NullString
	ID     int64
}

func (q *Queries) UpdateBuildInformation(ctx context.Context, arg UpdateBuildInformationParams) error {
	_, err := q.db.ExecContext(ctx, updateBuildInformation, arg.Status, arg.Logs, arg.ID)
	return err
}
