// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_deployment.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDatabaseDeployment = `-- name: CreateDatabaseDeployment :one
WITH new_deployment AS (
    INSERT INTO deployments (name, port, environment_id)
    VALUES ($1, $2, $3)
    RETURNING id, name, port, status, environment_id, created_at, updated_at
),
new_database_deployment AS (
    INSERT INTO database_deployments (deployment_id)
    SELECT id FROM new_deployment
    RETURNING deployment_id, username, password, created_at, updated_at
)
SELECT
    d.id AS deployment_id,
    d.name,
    d.port,
    d.environment_id,
    db.username,
    db.password
FROM new_deployment d
INNER JOIN new_database_deployment db ON d.id = db.deployment_id
`

type CreateDatabaseDeploymentParams struct {
	Name          string
	Port          string
	EnvironmentID int64
}

type CreateDatabaseDeploymentRow struct {
	DeploymentID  int64
	Name          string
	Port          string
	EnvironmentID int64
	Username      sql.NullString
	Password      sql.NullString
}

func (q *Queries) CreateDatabaseDeployment(ctx context.Context, arg CreateDatabaseDeploymentParams) (CreateDatabaseDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, createDatabaseDeployment, arg.Name, arg.Port, arg.EnvironmentID)
	var i CreateDatabaseDeploymentRow
	err := row.Scan(
		&i.DeploymentID,
		&i.Name,
		&i.Port,
		&i.EnvironmentID,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getEnvironmentDatabaseDeployments = `-- name: GetEnvironmentDatabaseDeployments :many
SELECT
    d.id AS deployment_id,
    d.name,
    d.port,
    d.status,
    d.environment_id,
    db.username,
    db.password
FROM deployments d
INNER JOIN database_deployments db ON d.id = db.deployment_id
INNER JOIN environments ON d.environment_id = environments.id
INNER JOIN projects ON environments.project_id = projects.id
INNER JOIN organizations ON organizations.id = projects.organization_id
INNER JOIN users ON users.id = organizations.owner_id
WHERE environment_id = $1
AND users.id = $2
ORDER BY d.id DESC
`

type GetEnvironmentDatabaseDeploymentsParams struct {
	EnvironmentID int64
	ID            int64
}

type GetEnvironmentDatabaseDeploymentsRow struct {
	DeploymentID  int64
	Name          string
	Port          string
	Status        DeploymentStatus
	EnvironmentID int64
	Username      sql.NullString
	Password      sql.NullString
}

func (q *Queries) GetEnvironmentDatabaseDeployments(ctx context.Context, arg GetEnvironmentDatabaseDeploymentsParams) ([]GetEnvironmentDatabaseDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnvironmentDatabaseDeployments, arg.EnvironmentID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnvironmentDatabaseDeploymentsRow
	for rows.Next() {
		var i GetEnvironmentDatabaseDeploymentsRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Name,
			&i.Port,
			&i.Status,
			&i.EnvironmentID,
			&i.Username,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatabaseDeploymentCredentials = `-- name: UpdateDatabaseDeploymentCredentials :exec
UPDATE database_deployments
SET username = $1,
    password = $2
WHERE deployment_id = $3
`

type UpdateDatabaseDeploymentCredentialsParams struct {
	Username     sql.NullString
	Password     sql.NullString
	DeploymentID int64
}

func (q *Queries) UpdateDatabaseDeploymentCredentials(ctx context.Context, arg UpdateDatabaseDeploymentCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, updateDatabaseDeploymentCredentials, arg.Username, arg.Password, arg.DeploymentID)
	return err
}
