// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: database_deployment.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDatabaseDeployment = `-- name: CreateDatabaseDeployment :one
WITH new_deployment AS (
  INSERT INTO deployments (
    name,
    port,
    environment_id)
  VALUES (
    $1,
    $2,
    $3)
RETURNING id, name, port, status, environment_id, created_at, updated_at, status_logs, deleted_at, rollout_status
),
new_database_deployment AS (
  INSERT INTO database_deployments (
    deployment_id)
  SELECT id
  FROM new_deployment
  RETURNING deployment_id, username, password, created_at, updated_at, database
)
SELECT d.id AS deployment_id,
  d.name,
  d.port,
  d.environment_id,
  db.username,
  db.password
FROM new_deployment d
  INNER JOIN new_database_deployment db ON d.id = db.deployment_id
`

type CreateDatabaseDeploymentParams struct {
	Name          string
	Port          string
	EnvironmentID sql.NullInt64
}

type CreateDatabaseDeploymentRow struct {
	DeploymentID  int64
	Name          string
	Port          string
	EnvironmentID sql.NullInt64
	Username      sql.NullString
	Password      sql.NullString
}

func (q *Queries) CreateDatabaseDeployment(ctx context.Context, arg CreateDatabaseDeploymentParams) (CreateDatabaseDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, createDatabaseDeployment, arg.Name, arg.Port, arg.EnvironmentID)
	var i CreateDatabaseDeploymentRow
	err := row.Scan(
		&i.DeploymentID,
		&i.Name,
		&i.Port,
		&i.EnvironmentID,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getDatabaseDeploymentById = `-- name: GetDatabaseDeploymentById :one
SELECT d.id AS deployment_id,
  d.name,
  d.port,
  d.status,
  d.environment_id,
  db.database,
  db.username,
  db.password
FROM deployments d
  INNER JOIN database_deployments db ON d.id = db.deployment_id
WHERE d.id = $1
  AND d.deleted_at IS NULL
`

type GetDatabaseDeploymentByIdRow struct {
	DeploymentID  int64
	Name          string
	Port          string
	Status        DeploymentStatus
	EnvironmentID sql.NullInt64
	Database      sql.NullString
	Username      sql.NullString
	Password      sql.NullString
}

func (q *Queries) GetDatabaseDeploymentById(ctx context.Context, deploymentID int64) (GetDatabaseDeploymentByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseDeploymentById, deploymentID)
	var i GetDatabaseDeploymentByIdRow
	err := row.Scan(
		&i.DeploymentID,
		&i.Name,
		&i.Port,
		&i.Status,
		&i.EnvironmentID,
		&i.Database,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getEnvironmentDatabaseDeployments = `-- name: GetEnvironmentDatabaseDeployments :many
SELECT d.id AS deployment_id,
  d.name,
  d.port,
  d.status,
  d.environment_id,
  db.database,
  db.username,
  db.password
FROM deployments d
  INNER JOIN database_deployments db ON d.id = db.deployment_id
  INNER JOIN environments ON d.environment_id = environments.id
WHERE environment_id = $1
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
`

type GetEnvironmentDatabaseDeploymentsRow struct {
	DeploymentID  int64
	Name          string
	Port          string
	Status        DeploymentStatus
	EnvironmentID sql.NullInt64
	Database      sql.NullString
	Username      sql.NullString
	Password      sql.NullString
}

func (q *Queries) GetEnvironmentDatabaseDeployments(ctx context.Context, environmentID sql.NullInt64) ([]GetEnvironmentDatabaseDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnvironmentDatabaseDeployments, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnvironmentDatabaseDeploymentsRow
	for rows.Next() {
		var i GetEnvironmentDatabaseDeploymentsRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Name,
			&i.Port,
			&i.Status,
			&i.EnvironmentID,
			&i.Database,
			&i.Username,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatabaseDeploymentCredentials = `-- name: UpdateDatabaseDeploymentCredentials :exec
UPDATE
  database_deployments
SET DATABASE = $1,
  username = $2,
  password = $3
WHERE deployment_id = $4
`

type UpdateDatabaseDeploymentCredentialsParams struct {
	Database     sql.NullString
	Username     sql.NullString
	Password     sql.NullString
	DeploymentID int64
}

func (q *Queries) UpdateDatabaseDeploymentCredentials(ctx context.Context, arg UpdateDatabaseDeploymentCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, updateDatabaseDeploymentCredentials,
		arg.Database,
		arg.Username,
		arg.Password,
		arg.DeploymentID,
	)
	return err
}
