// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getDeploymentById = `-- name: GetDeploymentById :one
SELECT deployments.id, deployments.name, deployments.port, deployments.status, deployments.environment_id, deployments.created_at, deployments.updated_at, deployments.status_logs, deployments.deleted_at, deployments.rollout_status
FROM deployments
WHERE deployments.id = $1
  AND deployments.deleted_at IS NULL
`

func (q *Queries) GetDeploymentById(ctx context.Context, deploymentID int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentById, deploymentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.Status,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusLogs,
		&i.DeletedAt,
		&i.RolloutStatus,
	)
	return i, err
}

const getDeploymentStatusLogs = `-- name: GetDeploymentStatusLogs :one
SELECT d.status_logs,
  d.rollout_status
FROM deployments d
WHERE d.id = $1
  AND d.deleted_at IS NULL
`

type GetDeploymentStatusLogsRow struct {
	StatusLogs    sql.NullString
	RolloutStatus string
}

func (q *Queries) GetDeploymentStatusLogs(ctx context.Context, deploymentID int64) (GetDeploymentStatusLogsRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStatusLogs, deploymentID)
	var i GetDeploymentStatusLogsRow
	err := row.Scan(&i.StatusLogs, &i.RolloutStatus)
	return i, err
}

const getDeploymentWithNamespace = `-- name: GetDeploymentWithNamespace :one
SELECT deployments.id, deployments.name, deployments.port, deployments.status, deployments.environment_id, deployments.created_at, deployments.updated_at, deployments.status_logs, deployments.deleted_at, deployments.rollout_status,
  environments.namespace
FROM deployments
  INNER JOIN environments ON deployments.environment_id = environments.id
WHERE deployments.id = $1
`

type GetDeploymentWithNamespaceRow struct {
	ID            int64
	Name          string
	Port          string
	Status        DeploymentStatus
	EnvironmentID sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	StatusLogs    sql.NullString
	DeletedAt     sql.NullTime
	RolloutStatus string
	Namespace     string
}

func (q *Queries) GetDeploymentWithNamespace(ctx context.Context, id int64) (GetDeploymentWithNamespaceRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentWithNamespace, id)
	var i GetDeploymentWithNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.Status,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusLogs,
		&i.DeletedAt,
		&i.RolloutStatus,
		&i.Namespace,
	)
	return i, err
}

const getDeploymentsWithKubeconfig = `-- name: GetDeploymentsWithKubeconfig :many
SELECT deployments.id, deployments.name, deployments.port, deployments.status, deployments.environment_id, deployments.created_at, deployments.updated_at, deployments.status_logs, deployments.deleted_at, deployments.rollout_status,
  c.kubeconfig,
  environments.namespace,
  c.id AS cluster_id,
  c.provisioning_id,
  c.organization_id
FROM deployments
  INNER JOIN environments ON deployments.environment_id = environments.id
  INNER JOIN projects ON environments.project_id = projects.id
  INNER JOIN clusters c ON c.id = projects.cluster_id
WHERE deployments.deleted_at IS NULL
`

type GetDeploymentsWithKubeconfigRow struct {
	ID             int64
	Name           string
	Port           string
	Status         DeploymentStatus
	EnvironmentID  sql.NullInt64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	StatusLogs     sql.NullString
	DeletedAt      sql.NullTime
	RolloutStatus  string
	Kubeconfig     sql.NullString
	Namespace      string
	ClusterID      int64
	ProvisioningID sql.NullString
	OrganizationID int64
}

func (q *Queries) GetDeploymentsWithKubeconfig(ctx context.Context) ([]GetDeploymentsWithKubeconfigRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsWithKubeconfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsWithKubeconfigRow
	for rows.Next() {
		var i GetDeploymentsWithKubeconfigRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Port,
			&i.Status,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StatusLogs,
			&i.DeletedAt,
			&i.RolloutStatus,
			&i.Kubeconfig,
			&i.Namespace,
			&i.ClusterID,
			&i.ProvisioningID,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentDeploymentByName = `-- name: GetEnvironmentDeploymentByName :one
SELECT deployments.id, deployments.name, deployments.port, deployments.status, deployments.environment_id, deployments.created_at, deployments.updated_at, deployments.status_logs, deployments.deleted_at, deployments.rollout_status
FROM deployments
WHERE deployments.name = $1
  AND environment_id = $2
  AND deleted_at IS NULL
`

type GetEnvironmentDeploymentByNameParams struct {
	Name          string
	EnvironmentID sql.NullInt64
}

func (q *Queries) GetEnvironmentDeploymentByName(ctx context.Context, arg GetEnvironmentDeploymentByNameParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentDeploymentByName, arg.Name, arg.EnvironmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.Status,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusLogs,
		&i.DeletedAt,
		&i.RolloutStatus,
	)
	return i, err
}

const setDeploymentStatusLogs = `-- name: SetDeploymentStatusLogs :exec
UPDATE
  deployments
SET status_logs = $1,
  rollout_status = $2
WHERE id = $3
`

type SetDeploymentStatusLogsParams struct {
	Logs          sql.NullString
	RolloutStatus string
	DeploymentID  int64
}

func (q *Queries) SetDeploymentStatusLogs(ctx context.Context, arg SetDeploymentStatusLogsParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentStatusLogs, arg.Logs, arg.RolloutStatus, arg.DeploymentID)
	return err
}

const softDeleteDeployment = `-- name: SoftDeleteDeployment :exec
UPDATE
  deployments
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDeployment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteDeployment, id)
	return err
}

const softDeleteDeploymentsByEnvironmentId = `-- name: SoftDeleteDeploymentsByEnvironmentId :exec
UPDATE
  deployments
SET deleted_at = NOW()
WHERE environment_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDeploymentsByEnvironmentId(ctx context.Context, environmentID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, softDeleteDeploymentsByEnvironmentId, environmentID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE
  deployments
SET status = $1::deployment_status
WHERE id = $2
  AND deleted_at IS NULL
`

type UpdateDeploymentStatusParams struct {
	Status DeploymentStatus
	ID     int64
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}
