// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments
WHERE id = $1
`

func (q *Queries) DeleteDeployment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, id)
	return err
}

const getDeploymentWithNamespace = `-- name: GetDeploymentWithNamespace :one
SELECT deployments.id, deployments.name, deployments.port, deployments.status, deployments.environment_id, deployments.created_at, deployments.updated_at, environments.namespace
FROM deployments
  INNER JOIN environments ON deployments.environment_id = environments.id
WHERE deployments.id = $1
`

type GetDeploymentWithNamespaceRow struct {
	ID            int64
	Name          string
	Port          string
	Status        DeploymentStatus
	EnvironmentID sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Namespace     string
}

func (q *Queries) GetDeploymentWithNamespace(ctx context.Context, id int64) (GetDeploymentWithNamespaceRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentWithNamespace, id)
	var i GetDeploymentWithNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.Status,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Namespace,
	)
	return i, err
}

const getDeploymentsWithKubeconfig = `-- name: GetDeploymentsWithKubeconfig :many
SELECT deployments.id, deployments.name, deployments.port, deployments.status, deployments.environment_id, deployments.created_at, deployments.updated_at, c.kubeconfig, environments.namespace
FROM deployments
  INNER JOIN environments ON deployments.environment_id = environments.id
  INNER JOIN projects ON environments.project_id = projects.id
  INNER JOIN clusters c ON c.id = projects.cluster_id
`

type GetDeploymentsWithKubeconfigRow struct {
	ID            int64
	Name          string
	Port          string
	Status        DeploymentStatus
	EnvironmentID sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Kubeconfig    sql.NullString
	Namespace     string
}

func (q *Queries) GetDeploymentsWithKubeconfig(ctx context.Context) ([]GetDeploymentsWithKubeconfigRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsWithKubeconfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsWithKubeconfigRow
	for rows.Next() {
		var i GetDeploymentsWithKubeconfigRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Port,
			&i.Status,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kubeconfig,
			&i.Namespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentDeploymentByName = `-- name: GetEnvironmentDeploymentByName :one
SELECT deployments.id, deployments.name, deployments.port, deployments.status, deployments.environment_id, deployments.created_at, deployments.updated_at
FROM deployments
WHERE deployments.name = $1
  AND environment_id = $2
`

type GetEnvironmentDeploymentByNameParams struct {
	Name          string
	EnvironmentID sql.NullInt64
}

func (q *Queries) GetEnvironmentDeploymentByName(ctx context.Context, arg GetEnvironmentDeploymentByNameParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentDeploymentByName, arg.Name, arg.EnvironmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.Status,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDeployment = `-- name: GetUserDeployment :one
SELECT deployments.id, deployments.name, deployments.port, deployments.status, deployments.environment_id, deployments.created_at, deployments.updated_at
FROM deployments
  INNER JOIN environments ON deployments.environment_id = environments.id
  INNER JOIN projects ON environments.project_id = projects.id
  INNER JOIN teams ON projects.team_id = teams.id
  INNER JOIN team_members ON team_members.team_id = teams.id
WHERE deployments.id = $1
  AND team_members.user_id = $2
`

type GetUserDeploymentParams struct {
	DeploymentID int64
	UserID       int64
}

func (q *Queries) GetUserDeployment(ctx context.Context, arg GetUserDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getUserDeployment, arg.DeploymentID, arg.UserID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.Status,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE
  deployments
SET status = $1::deployment_status
WHERE id = $2
`

type UpdateDeploymentStatusParams struct {
	Status DeploymentStatus
	ID     int64
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}
