// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_arg.sql

package sqlc

import (
	"context"
)

const createGitDeploymentArg = `-- name: CreateGitDeploymentArg :one
INSERT INTO git_deployment_args (
  deployment_id, name, value)
VALUES (
  $1, $2, $3)
RETURNING id, deployment_id, name, value, created_at, updated_at
`

type CreateGitDeploymentArgParams struct {
	DeploymentID int64
	Name         string
	Value        string
}

func (q *Queries) CreateGitDeploymentArg(ctx context.Context, arg CreateGitDeploymentArgParams) (GitDeploymentArg, error) {
	row := q.db.QueryRowContext(ctx, createGitDeploymentArg, arg.DeploymentID, arg.Name, arg.Value)
	var i GitDeploymentArg
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArgsByDeploymentId = `-- name: DeleteArgsByDeploymentId :exec
DELETE FROM git_deployment_args
WHERE deployment_id = $1
`

func (q *Queries) DeleteArgsByDeploymentId(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteArgsByDeploymentId, deploymentID)
	return err
}

const getGitDeploymentArgs = `-- name: GetGitDeploymentArgs :many
SELECT da.name, da.value
FROM git_deployment_args da
WHERE da.deployment_id = $1
`

type GetGitDeploymentArgsRow struct {
	Name  string
	Value string
}

func (q *Queries) GetGitDeploymentArgs(ctx context.Context, deploymentID int64) ([]GetGitDeploymentArgsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGitDeploymentArgs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGitDeploymentArgsRow
	for rows.Next() {
		var i GetGitDeploymentArgsRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
