// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_arg.sql

package sqlc

import (
	"context"
)

const createDeploymentArg = `-- name: CreateDeploymentArg :one
INSERT INTO deployment_args (deployment_id, name, value)
VALUES ($1, $2, $3)
RETURNING id, deployment_id, name, value, created_at, updated_at
`

type CreateDeploymentArgParams struct {
	DeploymentID int64
	Name         string
	Value        string
}

func (q *Queries) CreateDeploymentArg(ctx context.Context, arg CreateDeploymentArgParams) (DeploymentArg, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentArg, arg.DeploymentID, arg.Name, arg.Value)
	var i DeploymentArg
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArgsByDeploymentId = `-- name: DeleteArgsByDeploymentId :exec
DELETE FROM deployment_args
WHERE deployment_id = $1
`

func (q *Queries) DeleteArgsByDeploymentId(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteArgsByDeploymentId, deploymentID)
	return err
}

const getDeploymentArgs = `-- name: GetDeploymentArgs :many
SELECT da.name, da.value
FROM deployment_args da
WHERE da.deployment_id = $1
`

type GetDeploymentArgsRow struct {
	Name  string
	Value string
}

func (q *Queries) GetDeploymentArgs(ctx context.Context, deploymentID int64) ([]GetDeploymentArgsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentArgs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentArgsRow
	for rows.Next() {
		var i GetDeploymentArgsRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
