// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_environment_var.sql

package sqlc

import (
	"context"
)

const deleteEnvVarsByDeploymentId = `-- name: DeleteEnvVarsByDeploymentId :exec
DELETE FROM deployment_environment_vars
WHERE deployment_id = $1
`

func (q *Queries) DeleteEnvVarsByDeploymentId(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvVarsByDeploymentId, deploymentID)
	return err
}

const getDeploymentEnvironmentVars = `-- name: GetDeploymentEnvironmentVars :many
SELECT ev.name, ev.value
FROM deployment_environment_vars ev
WHERE ev.deployment_id = $1
`

type GetDeploymentEnvironmentVarsRow struct {
	Name  string
	Value string
}

func (q *Queries) GetDeploymentEnvironmentVars(ctx context.Context, deploymentID int64) ([]GetDeploymentEnvironmentVarsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentEnvironmentVars, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentEnvironmentVarsRow
	for rows.Next() {
		var i GetDeploymentEnvironmentVarsRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
