// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment.sql

package sqlc

import (
	"context"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (
    name,
    slug,
    namespace,
    project_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, slug, project_id, created_at, updated_at, namespace
`

type CreateEnvironmentParams struct {
	Name      string
	Slug      string
	Namespace string
	ProjectID int64
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment,
		arg.Name,
		arg.Slug,
		arg.Namespace,
		arg.ProjectID,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Namespace,
	)
	return i, err
}

const getEnvironmentAuthorizedUsers = `-- name: GetEnvironmentAuthorizedUsers :many
SELECT u.id
FROM environments
INNER JOIN projects p ON p.id = environments.project_id
INNER JOIN organizations o ON o.id = p.organization_id
INNER JOIN users u ON o.owner_id = u.id
WHERE environments.id = $1
`

func (q *Queries) GetEnvironmentAuthorizedUsers(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getEnvironmentAuthorizedUsers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentById = `-- name: GetEnvironmentById :one
SELECT id, name, slug, project_id, created_at, updated_at, namespace
FROM environments
WHERE environments.id = $1
`

func (q *Queries) GetEnvironmentById(ctx context.Context, id int64) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentById, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Namespace,
	)
	return i, err
}

const getEnvironmentCluster = `-- name: GetEnvironmentCluster :one
SELECT clusters.id, clusters.name, clusters.ipv4_address, clusters.public_key, clusters.private_key, clusters.organization_id, clusters.provisioning_id, clusters.status, clusters.created_at, clusters.updated_at, clusters.kubeconfig
FROM environments
INNER JOIN projects ON projects.id = environments.project_id
INNER JOIN clusters ON projects.cluster_id = clusters.id
WHERE environments.id = $1
`

func (q *Queries) GetEnvironmentCluster(ctx context.Context, id int64) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ipv4Address,
		&i.PublicKey,
		&i.PrivateKey,
		&i.OrganizationID,
		&i.ProvisioningID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kubeconfig,
	)
	return i, err
}

const getEnvironmentWithProject = `-- name: GetEnvironmentWithProject :one
SELECT
    projects.id AS project_id,
    projects.name AS project_name,
    e.id AS environment_id,
    e.name AS environment_name
FROM environments e
INNER JOIN projects ON projects.id = e.project_id
WHERE e.id = $1
`

type GetEnvironmentWithProjectRow struct {
	ProjectID       int64
	ProjectName     string
	EnvironmentID   int64
	EnvironmentName string
}

func (q *Queries) GetEnvironmentWithProject(ctx context.Context, id int64) (GetEnvironmentWithProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentWithProject, id)
	var i GetEnvironmentWithProjectRow
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectName,
		&i.EnvironmentID,
		&i.EnvironmentName,
	)
	return i, err
}
