// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: git_deployment.sql

package sqlc

import (
	"context"
)

const createGitDeployment = `-- name: CreateGitDeployment :one
WITH new_deployment AS (
    INSERT INTO deployments (name, port, environment_id)
    VALUES ($1, $2, $3)
    RETURNING id, name, port, status, environment_id, created_at, updated_at
),
new_git_deployment AS (
    INSERT INTO git_deployments (deployment_id, url, project_path, dockerfile_path)
    SELECT id, $4, $5, $6 FROM new_deployment
    RETURNING deployment_id, url, project_path, dockerfile_path, created_at, updated_at
)
SELECT
    d.id AS deployment_id,
    d.name,
    d.port,
    d.environment_id,
    gd.url,
    gd.dockerfile_path,
    gd.project_path
FROM new_deployment d
INNER JOIN new_git_deployment gd ON d.id = gd.deployment_id
`

type CreateGitDeploymentParams struct {
	Name           string
	Port           string
	EnvironmentID  int64
	Url            string
	ProjectPath    string
	DockerfilePath string
}

type CreateGitDeploymentRow struct {
	DeploymentID   int64
	Name           string
	Port           string
	EnvironmentID  int64
	Url            string
	DockerfilePath string
	ProjectPath    string
}

func (q *Queries) CreateGitDeployment(ctx context.Context, arg CreateGitDeploymentParams) (CreateGitDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, createGitDeployment,
		arg.Name,
		arg.Port,
		arg.EnvironmentID,
		arg.Url,
		arg.ProjectPath,
		arg.DockerfilePath,
	)
	var i CreateGitDeploymentRow
	err := row.Scan(
		&i.DeploymentID,
		&i.Name,
		&i.Port,
		&i.EnvironmentID,
		&i.Url,
		&i.DockerfilePath,
		&i.ProjectPath,
	)
	return i, err
}
