// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_deployment.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createImageDeployment = `-- name: CreateImageDeployment :one
WITH new_deployment AS (
    INSERT INTO deployments (name, port, status, environment_id)
    VALUES ($1, $2, $3, $4)
    RETURNING id, name, port, status, environment_id, created_at, updated_at
),
new_image_deployment AS (
    INSERT INTO image_deployments (deployment_id, name, tag)
    SELECT id, $5, $6 FROM new_deployment
    RETURNING deployment_id, name, tag, created_at, updated_at
)
SELECT
    d.id AS deployment_id,
    d.status,
    d.name AS service_name,
    img_d.name AS image_name,
    img_d.tag AS image_tag,
    d.port,
    d.environment_id
FROM new_deployment d
INNER JOIN new_image_deployment img_d ON d.id = img_d.deployment_id
`

type CreateImageDeploymentParams struct {
	ServiceName   string
	Port          string
	Status        sql.NullString
	EnvironmentID int64
	ImageName     string
	Tag           string
}

type CreateImageDeploymentRow struct {
	DeploymentID  int64
	Status        sql.NullString
	ServiceName   string
	ImageName     string
	ImageTag      string
	Port          string
	EnvironmentID int64
}

func (q *Queries) CreateImageDeployment(ctx context.Context, arg CreateImageDeploymentParams) (CreateImageDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, createImageDeployment,
		arg.ServiceName,
		arg.Port,
		arg.Status,
		arg.EnvironmentID,
		arg.ImageName,
		arg.Tag,
	)
	var i CreateImageDeploymentRow
	err := row.Scan(
		&i.DeploymentID,
		&i.Status,
		&i.ServiceName,
		&i.ImageName,
		&i.ImageTag,
		&i.Port,
		&i.EnvironmentID,
	)
	return i, err
}

const getEnvironmentImageDeployments = `-- name: GetEnvironmentImageDeployments :many
SELECT
    d.id AS deployment_id,
    d.name AS service_name,
    d.port,
    d.status,
    d.environment_id,
    img_d.name AS image_name,
    img_d.tag
FROM deployments d
INNER JOIN image_deployments img_d ON d.id = img_d.deployment_id
INNER JOIN environments e ON d.environment_id = e.id
INNER JOIN projects ON e.project_id = projects.id
INNER JOIN organizations ON organizations.id = projects.organization_id
INNER JOIN users ON users.id = organizations.owner_id
WHERE environment_id = $1
AND users.id = $2
`

type GetEnvironmentImageDeploymentsParams struct {
	EnvironmentID int64
	ID            int64
}

type GetEnvironmentImageDeploymentsRow struct {
	DeploymentID  int64
	ServiceName   string
	Port          string
	Status        sql.NullString
	EnvironmentID int64
	ImageName     string
	Tag           string
}

func (q *Queries) GetEnvironmentImageDeployments(ctx context.Context, arg GetEnvironmentImageDeploymentsParams) ([]GetEnvironmentImageDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnvironmentImageDeployments, arg.EnvironmentID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnvironmentImageDeploymentsRow
	for rows.Next() {
		var i GetEnvironmentImageDeploymentsRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.ServiceName,
			&i.Port,
			&i.Status,
			&i.EnvironmentID,
			&i.ImageName,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
