// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_deployment.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDeploymentEnvVar = `-- name: CreateDeploymentEnvVar :one
INSERT INTO deployment_environment_vars (deployment_id, name, value)
VALUES ($1, $2, $3)
RETURNING id, deployment_id, name, value, created_at, updated_at
`

type CreateDeploymentEnvVarParams struct {
	DeploymentID int64
	Name         string
	Value        string
}

func (q *Queries) CreateDeploymentEnvVar(ctx context.Context, arg CreateDeploymentEnvVarParams) (DeploymentEnvironmentVar, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentEnvVar, arg.DeploymentID, arg.Name, arg.Value)
	var i DeploymentEnvironmentVar
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeploymentVolume = `-- name: CreateDeploymentVolume :one
INSERT INTO deployment_volumes (deployment_id, volume_size_mb)
VALUES ($1, $2)
RETURNING id, deployment_id, volume_size_mb, created_at, updated_at
`

type CreateDeploymentVolumeParams struct {
	DeploymentID int64
	VolumeSizeMb int32
}

func (q *Queries) CreateDeploymentVolume(ctx context.Context, arg CreateDeploymentVolumeParams) (DeploymentVolume, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentVolume, arg.DeploymentID, arg.VolumeSizeMb)
	var i DeploymentVolume
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.VolumeSizeMb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImageDeployment = `-- name: CreateImageDeployment :one
WITH new_deployment AS (
    INSERT INTO deployments (name, port, environment_id)
    VALUES ($1, $2, $3)
    RETURNING id, name, port, status, environment_id, created_at, updated_at
),
new_image_deployment AS (
    INSERT INTO image_deployments (deployment_id, name, tag)
    SELECT id, $4, $5 FROM new_deployment
    RETURNING deployment_id, name, tag, created_at, updated_at
)
SELECT
    d.id AS deployment_id,
    d.status,
    d.name AS service_name,
    img_d.name AS image_name,
    img_d.tag AS image_tag,
    d.port,
    d.environment_id
FROM new_deployment d
INNER JOIN new_image_deployment img_d ON d.id = img_d.deployment_id
`

type CreateImageDeploymentParams struct {
	ServiceName   string
	Port          string
	EnvironmentID int64
	ImageName     string
	Tag           string
}

type CreateImageDeploymentRow struct {
	DeploymentID  int64
	Status        DeploymentStatus
	ServiceName   string
	ImageName     string
	ImageTag      string
	Port          string
	EnvironmentID int64
}

func (q *Queries) CreateImageDeployment(ctx context.Context, arg CreateImageDeploymentParams) (CreateImageDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, createImageDeployment,
		arg.ServiceName,
		arg.Port,
		arg.EnvironmentID,
		arg.ImageName,
		arg.Tag,
	)
	var i CreateImageDeploymentRow
	err := row.Scan(
		&i.DeploymentID,
		&i.Status,
		&i.ServiceName,
		&i.ImageName,
		&i.ImageTag,
		&i.Port,
		&i.EnvironmentID,
	)
	return i, err
}

const getEnvironmentImageDeployments = `-- name: GetEnvironmentImageDeployments :many
SELECT
    d.id AS deployment_id,
    d.name AS service_name,
    d.port,
    d.status,
    d.environment_id,
    img_d.name AS image_name,
    img_d.tag,
    dv.volume_size_mb
FROM deployments d
INNER JOIN image_deployments img_d ON d.id = img_d.deployment_id
LEFT JOIN deployment_volumes dv ON d.id = dv.deployment_id
INNER JOIN environments e ON d.environment_id = e.id
INNER JOIN projects ON e.project_id = projects.id
INNER JOIN teams ON projects.team_id = teams.id
INNER JOIN team_members ON team_members.team_id = teams.id
WHERE environment_id = $1
AND team_members.user_id = $2
ORDER BY d.id DESC
`

type GetEnvironmentImageDeploymentsParams struct {
	EnvironmentID int64
	UserID        int64
}

type GetEnvironmentImageDeploymentsRow struct {
	DeploymentID  int64
	ServiceName   string
	Port          string
	Status        DeploymentStatus
	EnvironmentID int64
	ImageName     string
	Tag           string
	VolumeSizeMb  sql.NullInt32
}

func (q *Queries) GetEnvironmentImageDeployments(ctx context.Context, arg GetEnvironmentImageDeploymentsParams) ([]GetEnvironmentImageDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnvironmentImageDeployments, arg.EnvironmentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnvironmentImageDeploymentsRow
	for rows.Next() {
		var i GetEnvironmentImageDeploymentsRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.ServiceName,
			&i.Port,
			&i.Status,
			&i.EnvironmentID,
			&i.ImageName,
			&i.Tag,
			&i.VolumeSizeMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageDeployment = `-- name: UpdateImageDeployment :one
WITH updated_deployment AS (
    UPDATE deployments
        SET port = $1
        WHERE id = $2
        RETURNING id, name, port, status, environment_id, created_at, updated_at
),
updated_image_deployment AS (
 UPDATE image_deployments
     SET
         name = $3,
         tag  = $4
     WHERE deployment_id = (SELECT id FROM updated_deployment)
     RETURNING deployment_id, name, tag, created_at, updated_at
)
SELECT
    d.id AS deployment_id,
    d.status,
    d.name AS service_name,
    img_d.name AS image_name,
    img_d.tag AS image_tag,
    d.port,
    d.environment_id
FROM updated_deployment d
INNER JOIN updated_image_deployment img_d ON d.id = img_d.deployment_id
`

type UpdateImageDeploymentParams struct {
	Port         string
	DeploymentID int64
	ImageName    string
	Tag          string
}

type UpdateImageDeploymentRow struct {
	DeploymentID  int64
	Status        DeploymentStatus
	ServiceName   string
	ImageName     string
	ImageTag      string
	Port          string
	EnvironmentID int64
}

func (q *Queries) UpdateImageDeployment(ctx context.Context, arg UpdateImageDeploymentParams) (UpdateImageDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, updateImageDeployment,
		arg.Port,
		arg.DeploymentID,
		arg.ImageName,
		arg.Tag,
	)
	var i UpdateImageDeploymentRow
	err := row.Scan(
		&i.DeploymentID,
		&i.Status,
		&i.ServiceName,
		&i.ImageName,
		&i.ImageTag,
		&i.Port,
		&i.EnvironmentID,
	)
	return i, err
}
