// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BuildStatus string

const (
	BuildStatusQueued   BuildStatus = "queued"
	BuildStatusBuilding BuildStatus = "building"
	BuildStatusSuccess  BuildStatus = "success"
	BuildStatusFailure  BuildStatus = "failure"
)

func (e *BuildStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildStatus(s)
	case string:
		*e = BuildStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildStatus: %T", src)
	}
	return nil
}

type NullBuildStatus struct {
	BuildStatus BuildStatus
	Valid       bool // Valid is true if BuildStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildStatus), nil
}

type ClusterStatus string

const (
	ClusterStatusPending ClusterStatus = "pending"
	ClusterStatusRunning ClusterStatus = "running"
	ClusterStatusDeleted ClusterStatus = "deleted"
)

func (e *ClusterStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClusterStatus(s)
	case string:
		*e = ClusterStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClusterStatus: %T", src)
	}
	return nil
}

type NullClusterStatus struct {
	ClusterStatus ClusterStatus
	Valid         bool // Valid is true if ClusterStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClusterStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClusterStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClusterStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClusterStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClusterStatus), nil
}

type DeploymentStatus string

const (
	DeploymentStatusHealthy   DeploymentStatus = "healthy"
	DeploymentStatusUnhealthy DeploymentStatus = "unhealthy"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus
	Valid            bool // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type Provider string

const (
	ProviderHetzner Provider = "hetzner"
)

func (e *Provider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Provider(s)
	case string:
		*e = Provider(s)
	default:
		return fmt.Errorf("unsupported scan type for Provider: %T", src)
	}
	return nil
}

type NullProvider struct {
	Provider Provider
	Valid    bool // Valid is true if Provider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvider) Scan(value interface{}) error {
	if value == nil {
		ns.Provider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Provider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Provider), nil
}

type Build struct {
	ID           int64
	DeploymentID sql.NullInt64
	Status       BuildStatus
	Logs         sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CommitHash   sql.NullString
	Source       string
	ImageName    sql.NullString
}

type Cluster struct {
	ID             int64
	Name           string
	Ipv4Address    sql.NullString
	PublicKey      sql.NullString
	PrivateKey     sql.NullString
	OrganizationID int64
	ProvisioningID sql.NullString
	Status         ClusterStatus
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Kubeconfig     sql.NullString
	ServerType     string
	User           string
}

type DatabaseDeployment struct {
	DeploymentID int64
	Username     sql.NullString
	Password     sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Database     sql.NullString
}

type Deployment struct {
	ID            int64
	Name          string
	Port          string
	Status        DeploymentStatus
	EnvironmentID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DeploymentEnvironmentVar struct {
	ID           int64
	DeploymentID int64
	Name         string
	Value        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type DeploymentVolume struct {
	ID            int64
	DeploymentID  sql.NullInt64
	VolumeSizeMib int32
	MountPath     string
	DeletedAt     sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Environment struct {
	ID              int64
	Name            string
	Slug            string
	ProjectID       int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Namespace       string
	ConnectedBranch string
}

type GitDeployment struct {
	DeploymentID   int64
	Url            string
	ProjectPath    string
	DockerfilePath string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GitDeploymentArg struct {
	ID           int64
	DeploymentID int64
	Name         string
	Value        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type GithubApp struct {
	ID             int64
	InstallationID int64
	OrganizationID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ImageDeployment struct {
	DeploymentID int64
	Name         string
	Tag          string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type IngressDeployment struct {
	DeploymentID int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type IngressHost struct {
	ID           int64
	DeploymentID int64
	Host         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type IngressPath struct {
	ID            int64
	IngressHostID int64
	DeploymentID  int64
	Path          string
	PathType      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Organization struct {
	ID        int64
	Name      string
	Slug      string
	OwnerID   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationInvite struct {
	ID             uuid.UUID
	OrganizationID int64
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

type OrganizationMember struct {
	OrganizationID int64
	UserID         int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PreviewEnvironment struct {
	EnvironmentID      int64
	GithubRepositoryID int64
	PrNumber           int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Project struct {
	ID                         int64
	Name                       string
	TeamID                     int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	ClusterID                  sql.NullInt64
	PreviewEnvironmentsEnabled sql.NullBool
}

type ProvisioningCredential struct {
	ID             int64
	OrganizationID int64
	Provider       Provider
	Secret         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Team struct {
	ID             int64
	Slug           string
	OrganizationID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TeamCluster struct {
	TeamID    int64
	ClusterID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamMember struct {
	TeamID    int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamRepository struct {
	TeamID       int64
	GithubRepoID int64
	RepoName     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID           int64
	BetterAuthID string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
