// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addOrganizationMember = `-- name: AddOrganizationMember :exec
INSERT INTO organization_members (
  organization_id, user_id)
VALUES (
  $1, $2)
ON CONFLICT (
  organization_id, user_id)
  DO NOTHING
`

type AddOrganizationMemberParams struct {
	OrganizationID int64
	UserID         int64
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
  name, slug, owner_id)
VALUES (
  $1, $2, $3)
RETURNING id, name, slug, owner_id, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name    string
	Slug    string
	OwnerID int64
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization, arg.Name, arg.Slug, arg.OwnerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationInvite = `-- name: CreateOrganizationInvite :one
WITH new_invite AS (
  INSERT INTO organization_invites (
    organization_id, email, expires_at)
  VALUES (
    $1, $2, $3)
RETURNING id, organization_id, expires_at, created_at, email)
SELECT new_invite.id, new_invite.organization_id, new_invite.expires_at, new_invite.created_at, new_invite.email, organizations.name AS organization_name
FROM new_invite
  INNER JOIN organizations ON organizations.id = new_invite.organization_id
`

type CreateOrganizationInviteParams struct {
	OrganizationID int64
	Email          string
	ExpiresAt      time.Time
}

type CreateOrganizationInviteRow struct {
	ID               uuid.UUID
	OrganizationID   int64
	ExpiresAt        time.Time
	CreatedAt        time.Time
	Email            string
	OrganizationName string
}

func (q *Queries) CreateOrganizationInvite(ctx context.Context, arg CreateOrganizationInviteParams) (CreateOrganizationInviteRow, error) {
	row := q.db.QueryRowContext(ctx, createOrganizationInvite, arg.OrganizationID, arg.Email, arg.ExpiresAt)
	var i CreateOrganizationInviteRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
		&i.OrganizationName,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, owner_id, created_at, updated_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationInviteById = `-- name: GetOrganizationInviteById :one
SELECT organization_invites.id, organization_invites.organization_id, organization_invites.expires_at, organization_invites.created_at, organization_invites.email, organizations.name AS organization_name
FROM organization_invites
  INNER JOIN organizations ON organizations.id = organization_invites.organization_id
WHERE organization_invites.id = $1
`

type GetOrganizationInviteByIdRow struct {
	ID               uuid.UUID
	OrganizationID   int64
	ExpiresAt        time.Time
	CreatedAt        time.Time
	Email            string
	OrganizationName string
}

func (q *Queries) GetOrganizationInviteById(ctx context.Context, id uuid.UUID) (GetOrganizationInviteByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationInviteById, id)
	var i GetOrganizationInviteByIdRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
		&i.OrganizationName,
	)
	return i, err
}

const getOrganizationMembers = `-- name: GetOrganizationMembers :many
SELECT users.id, users.better_auth_id
FROM users
  INNER JOIN organization_members ON organization_members.user_id = users.id
WHERE organization_members.organization_id = $1
`

type GetOrganizationMembersRow struct {
	ID           int64
	BetterAuthID string
}

func (q *Queries) GetOrganizationMembers(ctx context.Context, organizationID int64) ([]GetOrganizationMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationMembersRow
	for rows.Next() {
		var i GetOrganizationMembersRow
		if err := rows.Scan(&i.ID, &i.BetterAuthID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationProvisioningCredential = `-- name: GetOrganizationProvisioningCredential :one
SELECT pc.organization_id, pc.provider, pc.secret
FROM provisioning_credentials pc
WHERE organization_id = $1
  AND provider = $2
`

type GetOrganizationProvisioningCredentialParams struct {
	OrganizationID int64
	Provider       Provider
}

type GetOrganizationProvisioningCredentialRow struct {
	OrganizationID int64
	Provider       Provider
	Secret         string
}

func (q *Queries) GetOrganizationProvisioningCredential(ctx context.Context, arg GetOrganizationProvisioningCredentialParams) (GetOrganizationProvisioningCredentialRow, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationProvisioningCredential, arg.OrganizationID, arg.Provider)
	var i GetOrganizationProvisioningCredentialRow
	err := row.Scan(&i.OrganizationID, &i.Provider, &i.Secret)
	return i, err
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT organizations.id, organizations.name, organizations.slug, organizations.owner_id, organizations.created_at, organizations.updated_at
FROM organizations
  INNER JOIN organization_members ON organization_members.organization_id = organizations.id
WHERE organization_members.user_id = $1
`

func (q *Queries) GetUserOrganizations(ctx context.Context, userID int64) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :exec
DELETE FROM organization_members
WHERE organization_members.organization_id = $1
  AND organization_members.user_id = $2
`

type RemoveOrganizationMemberParams struct {
	OrganizationID int64
	UserID         int64
}

func (q *Queries) RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const upsertProvisioningCredential = `-- name: UpsertProvisioningCredential :exec
INSERT INTO provisioning_credentials (
  organization_id, provider, secret)
VALUES (
  $1, $2, $3)
ON CONFLICT (
  organization_id, provider)
  DO UPDATE SET
    secret = EXCLUDED.secret
`

type UpsertProvisioningCredentialParams struct {
	OrganizationID int64
	Provider       Provider
	Secret         string
}

func (q *Queries) UpsertProvisioningCredential(ctx context.Context, arg UpsertProvisioningCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertProvisioningCredential, arg.OrganizationID, arg.Provider, arg.Secret)
	return err
}
