// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name,
    organization_id,
    cluster_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, organization_id, created_at, updated_at, cluster_id
`

type CreateProjectParams struct {
	Name           string
	OrganizationID int64
	ClusterID      sql.NullInt64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.OrganizationID, arg.ClusterID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterID,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects p
USING organizations o
WHERE p.organization_id = o.id
    AND p.id = $1
    AND o.owner_id = $2
`

type DeleteProjectParams struct {
	ID      int64
	OwnerID int64
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.ID, arg.OwnerID)
	return err
}

const getOrganizationProjects = `-- name: GetOrganizationProjects :many
SELECT
    projects.id as id,
    projects.name as name,
    projects.organization_id as organization_id,
    environments.id as environment_id,
    environments.name as environment_name,
    environments.slug as environment_slug,
    environments.created_at as created_at
FROM projects
INNER JOIN organizations ON projects.organization_id = organizations.id
INNER JOIN environments ON projects.id = environments.project_id
WHERE projects.organization_id = $1
ORDER BY environments.created_at
`

type GetOrganizationProjectsRow struct {
	ID              int64
	Name            string
	OrganizationID  int64
	EnvironmentID   int64
	EnvironmentName string
	EnvironmentSlug string
	CreatedAt       time.Time
}

func (q *Queries) GetOrganizationProjects(ctx context.Context, organizationID int64) ([]GetOrganizationProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizationProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationProjectsRow
	for rows.Next() {
		var i GetOrganizationProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.EnvironmentSlug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProject = `-- name: GetProject :many
SELECT
    projects.id as id,
    projects.name as name,
    projects.organization_id as organization_id,
    projects.cluster_id as cluster_id,
    environments.id as environment_id,
    environments.name as environment_name,
    environments.slug as environment_slug
FROM projects
INNER JOIN organizations ON projects.organization_id = organizations.id
INNER JOIN environments ON projects.id = environments.project_id
WHERE projects.id = $1
AND organizations.owner_id = $2
`

type GetProjectParams struct {
	ID      int64
	OwnerID int64
}

type GetProjectRow struct {
	ID              int64
	Name            string
	OrganizationID  int64
	ClusterID       sql.NullInt64
	EnvironmentID   int64
	EnvironmentName string
	EnvironmentSlug string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) ([]GetProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, getProject, arg.ID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectRow
	for rows.Next() {
		var i GetProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.ClusterID,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.EnvironmentSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectCluster = `-- name: GetProjectCluster :one
SELECT c.id, c.name
FROM projects p
INNER JOIN clusters c ON p.cluster_id = c.id
INNER JOIN organizations o ON o.id = p.organization_id
WHERE p.id = $1
    AND o.owner_id = $2
`

type GetProjectClusterParams struct {
	ID      int64
	OwnerID int64
}

type GetProjectClusterRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetProjectCluster(ctx context.Context, arg GetProjectClusterParams) (GetProjectClusterRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectCluster, arg.ID, arg.OwnerID)
	var i GetProjectClusterRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
