// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name,
    team_id,
    cluster_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, team_id, created_at, updated_at, cluster_id, preview_environments_enabled
`

type CreateProjectParams struct {
	Name      string
	TeamID    int64
	ClusterID sql.NullInt64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.TeamID, arg.ClusterID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterID,
		&i.PreviewEnvironmentsEnabled,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects p
USING organizations o, teams t
WHERE t.organization_id = o.id
  AND p.team_id = t.id
  AND p.id = $1
  AND o.owner_id = $2
`

type DeleteProjectParams struct {
	ID      int64
	OwnerID int64
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.ID, arg.OwnerID)
	return err
}

const getProject = `-- name: GetProject :many
SELECT
    projects.id as id,
    projects.name as name,
    projects.team_id as team_id,
    projects.cluster_id as cluster_id,
    environments.id as environment_id,
    environments.name as environment_name,
    environments.slug as environment_slug
FROM projects
INNER JOIN teams ON projects.team_id = teams.id
INNER JOIN team_members ON teams.id = team_members.team_id
INNER JOIN environments ON projects.id = environments.project_id
WHERE projects.id = $1
    AND team_members.user_id = $2
`

type GetProjectParams struct {
	ID     int64
	UserID int64
}

type GetProjectRow struct {
	ID              int64
	Name            string
	TeamID          int64
	ClusterID       sql.NullInt64
	EnvironmentID   int64
	EnvironmentName string
	EnvironmentSlug string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) ([]GetProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, getProject, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectRow
	for rows.Next() {
		var i GetProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.ClusterID,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.EnvironmentSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectCluster = `-- name: GetProjectCluster :one
SELECT c.id, c.name
FROM projects p
INNER JOIN clusters c ON p.cluster_id = c.id
INNER JOIN teams t ON p.team_id = t.id
INNER JOIN team_members tm ON tm.team_id = t.id
WHERE p.id = $1
  AND tm.user_id = $2
`

type GetProjectClusterParams struct {
	ID     int64
	UserID int64
}

type GetProjectClusterRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetProjectCluster(ctx context.Context, arg GetProjectClusterParams) (GetProjectClusterRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectCluster, arg.ID, arg.UserID)
	var i GetProjectClusterRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getProjectEnvironments = `-- name: GetProjectEnvironments :many
SELECT e.id, e.name, e.slug, e.project_id, e.created_at, e.updated_at, e.namespace, e.connected_branch
FROM environments e
         INNER JOIN projects p ON p.id = e.project_id
         INNER JOIN teams t ON t.id = p.team_id
         INNER JOIN team_members tm ON tm.team_id = t.id
WHERE e.project_id = $1 AND tm.user_id = $2
`

type GetProjectEnvironmentsParams struct {
	ProjectID int64
	UserID    int64
}

func (q *Queries) GetProjectEnvironments(ctx context.Context, arg GetProjectEnvironmentsParams) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, getProjectEnvironments, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Namespace,
			&i.ConnectedBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectPreviewEnvironmentEnabled = `-- name: GetProjectPreviewEnvironmentEnabled :one
SELECT p.preview_environments_enabled
FROM projects p
    INNER JOIN teams t ON t.id = p.team_id
    INNER JOIN team_members tm ON tm.team_id = t.id
WHERE p.id = $1 AND tm.user_id = $2
`

type GetProjectPreviewEnvironmentEnabledParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetProjectPreviewEnvironmentEnabled(ctx context.Context, arg GetProjectPreviewEnvironmentEnabledParams) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, getProjectPreviewEnvironmentEnabled, arg.ID, arg.UserID)
	var preview_environments_enabled sql.NullBool
	err := row.Scan(&preview_environments_enabled)
	return preview_environments_enabled, err
}

const getProjectProductionEnvironmentsByRepositoryUrl = `-- name: GetProjectProductionEnvironmentsByRepositoryUrl :many
SELECT e.id, e.name, e.slug, e.project_id, e.created_at, e.updated_at, e.namespace, e.connected_branch
FROM environments e
WHERE e.name = 'Production'
  AND EXISTS (
    SELECT 1
    FROM deployments d
             JOIN git_deployments g ON g.deployment_id = d.id
    WHERE d.environment_id = e.id
      AND g.url = $1
)
`

func (q *Queries) GetProjectProductionEnvironmentsByRepositoryUrl(ctx context.Context, url string) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, getProjectProductionEnvironmentsByRepositoryUrl, url)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Namespace,
			&i.ConnectedBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProjects = `-- name: GetUserProjects :many
SELECT
    projects.id as id,
    projects.name as name,
    projects.team_id as team_id,
    environments.id as environment_id,
    environments.name as environment_name,
    environments.slug as environment_slug,
    environments.created_at as created_at
FROM projects
INNER JOIN teams ON projects.team_id = teams.id
INNER JOIN team_members ON teams.id = team_members.team_id
INNER JOIN environments ON projects.id = environments.project_id
WHERE teams.organization_id = $1
  AND team_members.user_id = $2
ORDER BY environments.created_at
`

type GetUserProjectsParams struct {
	OrganizationID int64
	UserID         int64
}

type GetUserProjectsRow struct {
	ID              int64
	Name            string
	TeamID          int64
	EnvironmentID   int64
	EnvironmentName string
	EnvironmentSlug string
	CreatedAt       time.Time
}

func (q *Queries) GetUserProjects(ctx context.Context, arg GetUserProjectsParams) ([]GetUserProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserProjects, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserProjectsRow
	for rows.Next() {
		var i GetUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.EnvironmentSlug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleProjectPreviewEnvironmentEnabled = `-- name: ToggleProjectPreviewEnvironmentEnabled :one
UPDATE projects p
SET preview_environments_enabled = NOT p.preview_environments_enabled
FROM teams t
         INNER JOIN team_members tm ON tm.team_id = t.id
WHERE p.team_id = t.id
  AND p.id = $1
  AND tm.user_id = $2
RETURNING p.preview_environments_enabled
`

type ToggleProjectPreviewEnvironmentEnabledParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) ToggleProjectPreviewEnvironmentEnabled(ctx context.Context, arg ToggleProjectPreviewEnvironmentEnabledParams) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, toggleProjectPreviewEnvironmentEnabled, arg.ID, arg.UserID)
	var preview_environments_enabled sql.NullBool
	err := row.Scan(&preview_environments_enabled)
	return preview_environments_enabled, err
}
