// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runner.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createRunner = `-- name: CreateRunner :one
INSERT INTO runners (
  organization_id)
VALUES (
  $1)
RETURNING id, organization_id, name, status, labels, max_concurrent_jobs, disabled_at, created_at, updated_at
`

func (q *Queries) CreateRunner(ctx context.Context, organizationID sql.NullInt64) (Runner, error) {
	row := q.db.QueryRowContext(ctx, createRunner, organizationID)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Status,
		pq.Array(&i.Labels),
		&i.MaxConcurrentJobs,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRunnerRegistrationToken = `-- name: CreateRunnerRegistrationToken :one
INSERT INTO runner_registration_tokens (
  organization_id,
  token_hash,
  expires_at,
  runner_id)
VALUES (
  $1,
  $2,
  $3,
  $4)
RETURNING id, organization_id, token_hash, expires_at, used_at, runner_id, created_at, updated_at
`

type CreateRunnerRegistrationTokenParams struct {
	OrganizationID sql.NullInt64
	TokenHash      string
	ExpiresAt      time.Time
	RunnerID       sql.NullInt64
}

func (q *Queries) CreateRunnerRegistrationToken(ctx context.Context, arg CreateRunnerRegistrationTokenParams) (RunnerRegistrationToken, error) {
	row := q.db.QueryRowContext(ctx, createRunnerRegistrationToken,
		arg.OrganizationID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RunnerID,
	)
	var i RunnerRegistrationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RunnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRunnerOnRegistration = `-- name: UpdateRunnerOnRegistration :one
UPDATE
  runners
SET name = $2,
  labels = $3,
  max_concurrent_jobs = $4
WHERE id = $1
RETURNING id, organization_id, name, status, labels, max_concurrent_jobs, disabled_at, created_at, updated_at
`

type UpdateRunnerOnRegistrationParams struct {
	ID                int64
	Name              sql.NullString
	Labels            []string
	MaxConcurrentJobs int32
}

func (q *Queries) UpdateRunnerOnRegistration(ctx context.Context, arg UpdateRunnerOnRegistrationParams) (Runner, error) {
	row := q.db.QueryRowContext(ctx, updateRunnerOnRegistration,
		arg.ID,
		arg.Name,
		pq.Array(arg.Labels),
		arg.MaxConcurrentJobs,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Status,
		pq.Array(&i.Labels),
		&i.MaxConcurrentJobs,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const useRunnerRegistrationToken = `-- name: UseRunnerRegistrationToken :one
UPDATE
  runner_registration_tokens
SET used_at = NOW()
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
RETURNING id, organization_id, token_hash, expires_at, used_at, runner_id, created_at, updated_at
`

func (q *Queries) UseRunnerRegistrationToken(ctx context.Context, tokenHash string) (RunnerRegistrationToken, error) {
	row := q.db.QueryRowContext(ctx, useRunnerRegistrationToken, tokenHash)
	var i RunnerRegistrationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RunnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
