// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runner.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createRunner = `-- name: CreateRunner :one
INSERT INTO runners (
  organization_id)
VALUES (
  $1)
RETURNING id, organization_id, name, status, labels, max_concurrent_jobs, disabled_at, created_at, updated_at
`

func (q *Queries) CreateRunner(ctx context.Context, organizationID sql.NullInt64) (Runner, error) {
	row := q.db.QueryRowContext(ctx, createRunner, organizationID)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Status,
		pq.Array(&i.Labels),
		&i.MaxConcurrentJobs,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRunnerRegistrationToken = `-- name: CreateRunnerRegistrationToken :one
INSERT INTO runner_registration_tokens (
  organization_id, token_hash, expires_at, runner_id)
VALUES (
  $1, $2, $3, $4)
RETURNING id, organization_id, token_hash, expires_at, used_at, runner_id, created_at, updated_at
`

type CreateRunnerRegistrationTokenParams struct {
	OrganizationID sql.NullInt64
	TokenHash      string
	ExpiresAt      time.Time
	RunnerID       sql.NullInt64
}

func (q *Queries) CreateRunnerRegistrationToken(ctx context.Context, arg CreateRunnerRegistrationTokenParams) (RunnerRegistrationToken, error) {
	row := q.db.QueryRowContext(ctx, createRunnerRegistrationToken,
		arg.OrganizationID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RunnerID,
	)
	var i RunnerRegistrationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RunnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
