// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package sqlc

import (
	"context"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (
    team_id,
    user_id
) VALUES (
    $1,
    $2
)
ON CONFLICT (team_id, user_id) DO NOTHING
`

type AddTeamMemberParams struct {
	TeamID int64
	UserID int64
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.UserID)
	return err
}

const assignRepoToTeam = `-- name: AssignRepoToTeam :exec
INSERT INTO team_repositories (
    team_id,
    github_repo_id,
    repo_name
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (team_id, github_repo_id) DO NOTHING
`

type AssignRepoToTeamParams struct {
	TeamID       int64
	GithubRepoID int64
	RepoName     string
}

func (q *Queries) AssignRepoToTeam(ctx context.Context, arg AssignRepoToTeamParams) error {
	_, err := q.db.ExecContext(ctx, assignRepoToTeam, arg.TeamID, arg.GithubRepoID, arg.RepoName)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    slug,
    organization_id
) VALUES (
    $1,
    $2
)
RETURNING id, slug, organization_id, created_at, updated_at
`

type CreateTeamParams struct {
	Slug           string
	OrganizationID int64
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.Slug, arg.OrganizationID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const deleteTeamIfEmpty = `-- name: DeleteTeamIfEmpty :exec
DELETE FROM teams
WHERE id = $1
    AND NOT EXISTS (
        SELECT 1 FROM team_members WHERE team_members.team_id = $1
    )
`

func (q *Queries) DeleteTeamIfEmpty(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeamIfEmpty, id)
	return err
}

const findTeamByIdAndUserId = `-- name: FindTeamByIdAndUserId :one
SELECT teams.id, teams.slug, teams.organization_id, teams.created_at, teams.updated_at
FROM teams
INNER JOIN organization_members ON organization_members.organization_id = teams.organization_id
WHERE teams.id = $1
    AND organization_members.user_id = $2
`

type FindTeamByIdAndUserIdParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) FindTeamByIdAndUserId(ctx context.Context, arg FindTeamByIdAndUserIdParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, findTeamByIdAndUserId, arg.ID, arg.UserID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamById = `-- name: GetTeamById :one
SELECT id, slug, organization_id, created_at, updated_at FROM teams WHERE teams.id = $1
`

func (q *Queries) GetTeamById(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamById, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, slug, organization_id, created_at, updated_at FROM teams
WHERE slug = $1 AND organization_id = $2
`

type GetTeamBySlugParams struct {
	Slug           string
	OrganizationID int64
}

func (q *Queries) GetTeamBySlug(ctx context.Context, arg GetTeamBySlugParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamBySlug, arg.Slug, arg.OrganizationID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT users.id, users.better_auth_id
FROM team_members
INNER JOIN users ON team_members.user_id = users.id
WHERE team_members.team_id = $1
`

type GetTeamMembersRow struct {
	ID           int64
	BetterAuthID string
}

func (q *Queries) GetTeamMembers(ctx context.Context, teamID int64) ([]GetTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersRow
	for rows.Next() {
		var i GetTeamMembersRow
		if err := rows.Scan(&i.ID, &i.BetterAuthID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamRepositories = `-- name: GetTeamRepositories :many
SELECT github_repo_id, repo_name
FROM team_repositories
WHERE team_id = $1
`

type GetTeamRepositoriesRow struct {
	GithubRepoID int64
	RepoName     string
}

func (q *Queries) GetTeamRepositories(ctx context.Context, teamID int64) ([]GetTeamRepositoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamRepositories, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamRepositoriesRow
	for rows.Next() {
		var i GetTeamRepositoriesRow
		if err := rows.Scan(&i.GithubRepoID, &i.RepoName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsByRepoAndOrg = `-- name: GetTeamsByRepoAndOrg :many
SELECT teams.id, teams.name, teams.slug, teams.organization_id, teams.created_at, teams.updated_at
FROM teams
INNER JOIN team_repositories ON team_repositories.team_id = teams.id
WHERE teams.organization_id = $1
    AND team_repositories.github_repo_id = $2
`

type GetTeamsByRepoAndOrgParams struct {
	OrganizationID int64
	GithubRepoID   int64
}

func (q *Queries) GetTeamsByRepoAndOrg(ctx context.Context, arg GetTeamsByRepoAndOrgParams) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeamsByRepoAndOrg, arg.OrganizationID, arg.GithubRepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTeams = `-- name: GetUserTeams :many
SELECT teams.id, teams.slug, teams.organization_id, teams.created_at, teams.updated_at
FROM teams
INNER JOIN team_members ON team_members.team_id = teams.id
WHERE teams.organization_id = $1
    AND team_members.user_id = $2
`

type GetUserTeamsParams struct {
	OrganizationID int64
	UserID         int64
}

func (q *Queries) GetUserTeams(ctx context.Context, arg GetUserTeamsParams) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getUserTeams, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE team_members.team_id = $1
    AND team_members.user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID int64
	UserID int64
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const unassignRepoFromTeam = `-- name: UnassignRepoFromTeam :exec
DELETE FROM team_repositories
WHERE team_id = $1
    AND github_repo_id = $2
`

type UnassignRepoFromTeamParams struct {
	TeamID       int64
	GithubRepoID int64
}

func (q *Queries) UnassignRepoFromTeam(ctx context.Context, arg UnassignRepoFromTeamParams) error {
	_, err := q.db.ExecContext(ctx, unassignRepoFromTeam, arg.TeamID, arg.GithubRepoID)
	return err
}
