tls:
  certificates:
    - certFile: /certs/dev.starliner.app.crt
      keyFile: /certs/dev.starliner.app.key
    - certFile: /certs/auth.dev.starliner.app.crt
      keyFile: /certs/auth.dev.starliner.app.key