name: Client Lint And Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  client-lint-and-test:
    if: '! github.event.pull_request.draft'
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.11.1'

      - name: Install dependencies
        run: npm install
        working-directory: client

      - name: Run Biome
        run: npx biome ci .
        working-directory: client

      - name: Run type check
        run: npm run typecheck
        working-directory: client

      - name: Run vulnerability check
        run: npm audit
        working-directory: client

      - name: Run tests
        run: npm run test:run
        working-directory: client