name: Server Linters
on:
  pull_request:
  workflow_dispatch:

jobs:
  server-lint:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"

      - name: Install pgFormatter
        run: |
          sudo apt-get update
          sudo apt-get install -y pgformatter

      - name: Check SQL formatting
        run: |
          find . -name "*.sql" -exec pg_format -i {} \;

          git diff --exit-code
        working-directory: server

      - name: Install Arch-Go
        run: go install -v github.com/arch-go/arch-go/v2@latest
        working-directory: server

      - name: Run architecture check
        run: |
          go mod download
          go mod verify
          arch-go
        working-directory: server

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
          working-directory: server

      - name: Run vulnerabilities check
        run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest ./...
        working-directory: server