name: Server Linters
on:
  pull_request:
  workflow_dispatch:

jobs:
  server-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.8"

      - name: Install Arch-Go
        run: go install -v github.com/arch-go/arch-go/v2@latest
        working-directory: server

      - name: Run architecture check
        run: |
          go mod download
          go mod verify
          arch-go
        working-directory: server

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          working-directory: server

      - name: Run vulnerabilities check
        run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest ./...
        working-directory: server