// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.5
// source: internal/infrastructure/nats/proto/v1/build.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Build struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Organization   string                 `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	Project        string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Service        string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	S3Key          string                 `protobuf:"bytes,5,opt,name=s3Key,proto3" json:"s3Key,omitempty"`
	RootDirectory  string                 `protobuf:"bytes,6,opt,name=rootDirectory,proto3" json:"rootDirectory,omitempty"`
	DockerfilePath string                 `protobuf:"bytes,7,opt,name=dockerfilePath,proto3" json:"dockerfilePath,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_internal_infrastructure_nats_proto_v1_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_nats_proto_v1_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_nats_proto_v1_build_proto_rawDescGZIP(), []int{0}
}

func (x *Build) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Build) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Build) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Build) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Build) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *Build) GetRootDirectory() string {
	if x != nil {
		return x.RootDirectory
	}
	return ""
}

func (x *Build) GetDockerfilePath() string {
	if x != nil {
		return x.DockerfilePath
	}
	return ""
}

var File_internal_infrastructure_nats_proto_v1_build_proto protoreflect.FileDescriptor

const file_internal_infrastructure_nats_proto_v1_build_proto_rawDesc = "" +
	"\n" +
	"1internal/infrastructure/nats/proto/v1/build.proto\x12\bproto.v1\"\xd3\x01\n" +
	"\x05Build\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\forganization\x18\x02 \x01(\tR\forganization\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x14\n" +
	"\x05s3Key\x18\x05 \x01(\tR\x05s3Key\x12$\n" +
	"\rrootDirectory\x18\x06 \x01(\tR\rrootDirectory\x12&\n" +
	"\x0edockerfilePath\x18\a \x01(\tR\x0edockerfilePathB\x18Z\x16starliner.app/proto/v1b\x06proto3"

var (
	file_internal_infrastructure_nats_proto_v1_build_proto_rawDescOnce sync.Once
	file_internal_infrastructure_nats_proto_v1_build_proto_rawDescData []byte
)

func file_internal_infrastructure_nats_proto_v1_build_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_nats_proto_v1_build_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_nats_proto_v1_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_nats_proto_v1_build_proto_rawDesc), len(file_internal_infrastructure_nats_proto_v1_build_proto_rawDesc)))
	})
	return file_internal_infrastructure_nats_proto_v1_build_proto_rawDescData
}

var file_internal_infrastructure_nats_proto_v1_build_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_infrastructure_nats_proto_v1_build_proto_goTypes = []any{
	(*Build)(nil), // 0: proto.v1.Build
}
var file_internal_infrastructure_nats_proto_v1_build_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_nats_proto_v1_build_proto_init() }
func file_internal_infrastructure_nats_proto_v1_build_proto_init() {
	if File_internal_infrastructure_nats_proto_v1_build_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_nats_proto_v1_build_proto_rawDesc), len(file_internal_infrastructure_nats_proto_v1_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_infrastructure_nats_proto_v1_build_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_nats_proto_v1_build_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_nats_proto_v1_build_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_nats_proto_v1_build_proto = out.File
	file_internal_infrastructure_nats_proto_v1_build_proto_goTypes = nil
	file_internal_infrastructure_nats_proto_v1_build_proto_depIdxs = nil
}
